### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by ionescu007** [joxeankoret/diaphora#1]
Hi,

When running the script on one of my IDB files, I receive the following error, and the .sqlite database is only 50KB and mostly NULLs. Any way to debug?

Error: Python int too large to convert to SQLite INTEGER
Traceback (most recent call last):
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 2400, in diff_or_export
    bd.export()
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 987, in export
    self.do_export()
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 979, in do_export
    self.save_function(props)
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 873, in save_function
    db_id = self_get_instruction_id(int(addr))
  File "C:/Program Files (x86)/IDA 6.7/plugins/diaphora-master/diaphora.py", line 819, in get_instruction_id
    cur.execute(sql, (addr,))

**Comment by joxeankoret** [comment]
Hi Alex,

The problem seems to be with the address BADADDR (which is -1). I'll fix it ASAP. However, I'm curious about why the address of the function is BADADDR (0xFFFFFFFF). Can you share the IDB? If posible, of course.

**Comment by joxeankoret** [comment]
This is my temporary diff:

```
--- a/diaphora.py
+++ b/diaphora.py
@@ -870,11 +870,14 @@ class CBinDiff:
       for key in bb_data:
         for insn in bb_data[key]:
           addr, mnem, disasm, cmt1, cmt2 = insn
-          db_id = self_get_instruction_id(int(addr))
-          if db_id is None:
-            cur_execute(sql, (addr, mnem, disasm, cmt1, cmt2))
-            db_id = cur.lastrowid
-          instructions_ids[addr] = db_id
+          # Why the instruction's address is BADADDR in some cases?
+          # Stil a mistery unless I can test with a repro IDB :(
+          if int(addr) != BADADDR:
+            db_id = self_get_instruction_id(int(addr))
+            if db_id is None:
+              cur_execute(sql, (addr, mnem, disasm, cmt1, cmt2))
+              db_id = cur.lastrowid
+            instructions_ids[addr] = db_id
 
       num = 0
       bb_ids = {}
```

**Comment by ionescu007** [comment]
I  will try to check and see where the BADADDR comes from, but I have seen
this before in the following cases:

- When gs or other segment selector accesses are done, which IDA doesn't
always understand. For example, in this IDB, there is code like "gs:8738h"
- When hard-coded addresses are used that are not part of any valid memory
IDA understands. For example, this IDB accesses some addresses at
0xFFFFFF870000000 or higher.

If you could trace out *where* the BADADDR is, I could see the instruction
in the IDB :)

I will try out your patch on Tuesday when I back on that machine.

Best regards,
Alex Ionescu

**Comment by joxeankoret** [comment]
Hi Alex,

I think I fixed the bug you found. I tried with various x64 kernel image files and, apparently (with OpenBSD, Linux and NetBSD kernels) all the Python's OverflowErrors should be fixed.

Please try with commit 5f1c3d5f7be45dad32cf6ee4d00dfe21360106f5 and tell me if it works for you.

**Comment by ionescu007** [comment]
This issue is now fixed
