### ISSUE TITLE
Update the documentation to reflect latest changes

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#10]
While not all changes will be permanent (I guess), 90% of them will be. The documentation must be updated. Both the tutorial and the heuristics part.

**Comment by raaka1** [comment]
Let me know, How can i help

**Comment by joxeankoret** [comment]
Updating the tutorial to reflect the latest changes to the UI and to document the heuristics (which I likely need to do myself).

**Comment by nanotechz9l** [comment]
@joxeankoret I've already started this. I've updated the current "diaphora_help.odt" document all the way up to the "Ignoring small differences (Finding new functionalities)" section. I emailed you a copy.

**Comment by joxeankoret** [comment]
Thanks @nanotechz9l ! I will take a look at some point this week (I'm know sick).

**Comment by joxeankoret** [comment]
Fixed completely with commit 1ad5b8ade8ae0e5590b39c2a4dacda375763e087
