### ISSUE TITLE
OnDeleteLine has been removed in 5351b6. Why?

### ISSUE THREAD

**Issue by AGG2017** [joxeankoret/diaphora#103]
I see that I can no longer delete a line from the result and found that OnDeleteLine has been removed in 5351b6. Is there any particular reason or it is done by mistake?

PS: Thanks for the fix for #84. I will test it more carefully when I come back from my vacation by the weekend. Just a few tests as far as I still have some stuff with me shows that all looks good except some minor problems with some of the asm comments still not imported. When I'm back I will provide more details for the issue (if any).

**Comment by joxeankoret** [comment]
Uhm... I have removed it because it should work without it. As I understand, it isn't so I broke something :/ OK, fixing it...

**Comment by joxeankoret** [comment]
And thanks a lot of reporting and extensively documenting the bug!

**Comment by joxeankoret** [comment]
Fixed!
