### ISSUE TITLE
Comment importing issue

### ISSUE THREAD

**Issue by AGG2017** [joxeankoret/diaphora#104]
After some tests I found that I still have problems to import some of the comments. It was easy to see some issues just by looking at your latest patch:
1. In import_instruction_level we need more complex check for the comments flag:
has_comments = str(ea2) in import_syms and ((import_syms[str(ea2)][1] is not None) or (import_syms[str(ea2)][2] is not None) or (import_syms[str(ea2)][6] is not None))
This will check for cmt1, cmt2 and pseudo comments instead of the current check for pseudo comments only.
2. In import_instruction the processing of cmt2 should be:
    if cmt2 is not None and get_cmt(ea1, 1) is None:
      set_cmt(ea1, cmt2, 1)

After these two changes I was able to import all comments that have been missing.
Thanks again for your great work!

**Comment by joxeankoret** [comment]
Thanks a lot! I will patch the bugs you reported this week.

**Comment by AGG2017** [comment]
Also I see that the local function user defined label names are not imported. The notebook with me is too small to see and test the code better in order to understand what change is needed and where. This is related to find where to include my code for that:
    #import the user defined local label names
    current_label = GetTrueNameEx(ea1,ea1)
    if current_label != new_label_name:
      MakeName(ea1, new_label_name)
If you know how this can be added please include it in your patch to finalize the import function. Otherwise when I'm back I will figure out what is the issue and will open separate ticket for that if there is a real problem. Thanks!

**Comment by AGG2017** [comment]
You can complete this case just for the comments for now. For the user defined labels I have to open another case later because I clearly see it is not possible to be fixed with the current DB structure as it is. As I explained in #84 we need to add label_name info in the instructions table and maybe to add also the operand label name as a name info in the same table.

**Comment by AGG2017** [comment]
In [my copy of the repo](https://github.com/AGG2017/diaphora) I added my temporary version for importing the user defined labels with just one commit after your current master HEAD. It imports all user labels without any issue. You can check it if you want to see what I did.

**Comment by joxeankoret** [comment]
Interesting, I will extract the portions specific to user defined labels and patch it. Thank you!

**Comment by AGG2017** [comment]
I'm sorry. I forgot to mention that it is my complete experimental version with everything else I needed. I hope it is not hard to see the part you may need.

**Comment by joxeankoret** [comment]
It's ok

**Comment by joxeankoret** [comment]
Applied a partial fix for the comments issue. The next part will be to add label names too.

**Comment by joxeankoret** [comment]
Added yet another partial fix for the instruction level importing multiple issues with commit https://github.com/joxeankoret/diaphora/commit/0820748e1bc5a66bdd2cc88172256f093ca5bed4.

**Comment by AGG2017** [comment]
I found this to be a potential issue but I was unable to understand this time which one of the sets is the imported one because of the query with "order by 2 asc". I'll do more tests to understand if this type of sorting will affect the proper processing.
