### ISSUE TITLE
Integer Overflow when creating SQLLite DB

### ISSUE THREAD

**Issue by FritzSandsTM** [joxeankoret/diaphora#106]
System -- Win 10 x64.
IDA -- Version 7.0.171130 Windows x64 (64-bit address size)
File -- win32k.sys

When building the SQLLite db, I get a Python failure:

---------------------------------------------------------------------------------------------
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
[Tue Jan 16 16:44:52 2018] Database 'C:\\Users\\ZDI\\Desktop\\win32k\\win32k\\Win 8.1 x64 20170303\\win32k.sqlite' removed
Error: Python int too large to convert to SQLite INTEGER
Traceback (most recent call last):
  File "C:/Users/ZDI/Documents/GitHub/diaphora\diaphora_ida.py", line 1788, in _diff_or_export
    bd.export()
  File "C:/Users/ZDI/Documents/GitHub/diaphora\diaphora_ida.py", line 599, in export
    self.do_export()
  File "C:/Users/ZDI/Documents/GitHub/diaphora\diaphora_ida.py", line 582, in do_export
    self.save_function(props)
  File "C:/Users/ZDI/Documents/GitHub/diaphora\diaphora.py", line 579, in save_function
    cur.execute(sql, (func_id, caller, 'caller'))
OverflowError: Python int too large to convert to SQLite INTEGER

After this, I wind up with a very small SQLLite DB.

**Comment by joxeankoret** [comment]
I thought I had removed all occurrences of this damn recurrent bug. Thanks for reporting! Will be fixed soon.

**Comment by joxeankoret** [comment]
Fixed with https://github.com/joxeankoret/diaphora/commit/514937898beee605d4454096cae7e124d181e0dc
