### ISSUE TITLE
'NoneType' has no len() - Diffing MachO Binary

### ISSUE THREAD

**Issue by machoreverser** [joxeankoret/diaphora#107]
Using IDA v7, I get the attached error. Any ideas? What other info can I provide to assist?
![ida error](https://user-images.githubusercontent.com/35755250/35315221-f8977e5a-007f-11e8-8894-aeb41e12607b.png)

**Comment by joxeankoret** [comment]
Curious bug. It seems to be because "all_functions_matched" is true. I will push a fix for it now. Thanks for reporting!

**Comment by joxeankoret** [comment]
Please check with the latest version.
