### ISSUE TITLE
Supporting both diff directions?

### ISSUE THREAD

**Issue by saidelike** [joxeankoret/diaphora#111]
# Test 1

I use `diaphora_load.py` to open a previously saved database called `lina924-25_vs_lina924-24.diaphora`. By default, it knows the paths of the respective `.sqlite` databases so it automatically loads them.

```
[Tue Feb 06 10:29:00 2018] Main database 'C:\original\path\lina924-25.sqlite'.
[Tue Feb 06 10:29:00 2018] Diff database 'C:\original\path\lina924-24.sqlite'.
[Tue Feb 06 10:29:01 2018] Showing diff results.
```
However when right-clicking a function (e.g. in "Partial matches") and selecting "Diff assembly", what I get is `lina924-25` on the left and `lina924-24` on the right. It would be easier to have it the other way around, i.e. having lina924-24 on the left and lina924-25 i.e. the oldest on the left and most recent on the right.

# Test 2

If you copy the files elsewhere and use again `diaphora_load.py`, it won't find the `.sqlite` files and prompt for us to the paths. So I tested both cases below.

## Test 2.1

In the first test, I select the right `lina924-25.sqlite` that it expects:

```
[Tue Feb 06 02:27:47 2018] Primary database C:\original\path\lina924-25.sqlite not found.
[Tue Feb 06 02:28:02 2018] Main database 'Z:\other\lina924-25.sqlite'.
[Tue Feb 06 02:28:02 2018] Diff database 'Z:\other\lina924-24.sqlite'.
```

I get the same result as Test 1.

## Test 2.2

In the second test, I select `lina924-24.sqlite` when it requests the primary database (= main database). I do that on purpose as I want it to be the base database and have `lina924-25.sqlite` be the diff database.

```
[Tue Feb 06 02:26:21 2018] Primary database C:\original\path\lina924-25.sqlite not found.
[Tue Feb 06 02:26:47 2018] Main database 'Z:\other\lina924-24.sqlite'.
[Tue Feb 06 02:26:47 2018] Diff database 'Z:\other\lina924-25.sqlite'.
[Tue Feb 06 02:26:49 2018] Showing diff results.
```

It loads fine and display all the matches windows. However as soon as I try to right-click a function (e.g. in "Partial matches") and selecting "Diff assembly", I get the following error: `Sorry, there is no assembly available for either the first or second database`

# Question

Would it be possible to support both directions after the diff has already been generated? Obviously, I could re-run Diaphora but it takes 8 hours to diff the binaries (40 MB each). I guess it is entirely my fault as I should have diffed them in the right order. Iirc what I did is I opened the newest binary (lina924-25) and tried to diff it against the old binary (lina924-24). So what I should have done is to open the old .idb (lina924-24) and diff it against the new one.

**Comment by joxeankoret** [comment]
Uhm... no promises, but I believe it's easy to support this feature. I will take a look to it...

**Comment by joxeankoret** [comment]
BTW, a quick & dirty hack so you don't have to do another 8 hours diff: just rename the databases.

**Comment by saidelike** [comment]
## Test 3

Thanks for the feedback. So interestingly I tried to rename them but it does not work. I get the same output as Test 1 as it finds the `.sqlite` databases:

```
[Tue Feb 06 14:37:47 2018] Main database 'C:\original\path\lina924-25.sqlite'.
[Tue Feb 06 14:37:47 2018] Diff database '\original\path\lina924-24.sqlite'.
[Tue Feb 06 14:37:48 2018] Showing diff results.
```

However as soon as I try to right-click a function (e.g. in "Partial matches") and selecting "Diff assembly", I get the same error: `Sorry, there is no assembly available for either the first or second database`.

**Comment by joxeankoret** [comment]
Uhm... this even more dirty workaround should work:

1. Make a backup of your diff (the *.diaphora file).
2. Open it with SQLite3 in a terminal and do the following:

```
$ sqlite3 your_file.diaphora
sqlite> update config set diff_db = main_db, main_db = diff_db ;
```

Remember to keep them renamed.

**Comment by joxeankoret** [comment]
I don't think it should be applied. Please re-open if somebody thinks it should be done.
