### ISSUE TITLE
Import selected fails (multi selection)

### ISSUE THREAD

**Issue by Harko** [joxeankoret/diaphora#112]
How to reproduce:
Tab 'Best matches', sort header 'Name 2', select multiple items and choose command 'Import selected'

   self.bindiff.import_selected(self.items, self.selected_items, cmd_id == self.cmd_import_selected_auto)

self.selected_items and self.items are no longer in the same order when the list gets resorted by clicking on a column header

**Comment by joxeankoret** [comment]
It looks like an IDAPython + choosers bug. Let me take a look to it to verify...

**Comment by joxeankoret** [comment]
Can you @Harko reproduce it with the latest version?

**Comment by joxeankoret** [comment]
Guess we can close it.
