### ISSUE TITLE
BUG: When choosing an idb and not an .sqlite during diffing, python get stuck in an endless loop

### ISSUE THREAD

**Issue by dummys** [joxeankoret/diaphora#113]
Hello,
Latest ida version on Linux.
The popup shows "python script running" and a warning is shown "Do not choose an idb".
It could be interesting to do the test before running the loop. The only way to close this is to crash ida.

**Comment by joxeankoret** [comment]
Uhm.. Do you see the message "One of the selected databases is an IDA file. Please select only database files" and then it keeps in the loop or that message doesn't even show up?

**Comment by dummys** [comment]
Yes I, see the message

**Comment by joxeankoret** [comment]
It makes no sense, there is a return immediately. Looks to me like an IDA Python bug. Let me verify...

**Comment by dummys** [comment]
will test tomorrow without any python plugins

On 15 Feb 2018 21:23, "Joxean" <notifications@github.com> wrote:

It makes no sense, there is a return immediately. Looks to me like an IDA
Python bug. Let me verify...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/joxeankoret/diaphora/issues/113#issuecomment-366050138>,
or mute the thread

**Comment by dummys** [comment]
ok you are right @joxeankoret. I'm sorry it's one of my plugin that do the looping stuff...
Need to search which one now :D

**Comment by joxeankoret** [comment]
I cannot reproduce with IDA 7.0 x64 for Linux :?

**Comment by dummys** [comment]
Yes ,latest version downloaded yesterday. Had a bunch of plugin like flare, with special idapythonrc.py. But for now didn't get the endless loop again. will further investigate and keep you posted. sorry for disturbing.

**Comment by joxeankoret** [comment]
You don't disturb, no worries.
