### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by gymgit** [joxeankoret/diaphora#114]
Hi, I am getting the following error, when trying to create the sqlite database. The target binary is an arm64 bootloader, if that is relevant.

```
[-18446744073675458560L, -18446744073675458556L, -18446744073675458556L, -18446744073675458552L, -18446744073675458548L, -18446744073675458544L, -18446744073675458540L, -18446744073675458540L, -18446744073675458536L, -18446744073675458532L, -18446744073675458532L, -18446744073675458528L, -18446744073675458524L, -18446744073675458520L, -18446744073675458516L, -18446744073675458512L, -18446744073675458512L, -18446744073675458508L, -18446744073675458504L, -18446744073675458504L, -18446744073675458500L, -18446744073675458500L, -18446744073675458496L, -18446744073675458492L, -18446744073675458488L, -18446744073675458484L, -18446744073675458480L, -18446744073675458476L, -18446744073675436532L, -18446744073675436532L]
Error: Python int too large to convert to SQLite INTEGER
Traceback (most recent call last):
  File "/home/user/progs/src/diaphora/diaphora_ida.py", line 1815, in _diff_or_export
    bd.export()
  File "/home/user/progs/src/diaphora/diaphora_ida.py", line 600, in export
    self.do_export()
  File "/home/user/progs/src/diaphora/diaphora_ida.py", line 583, in do_export
    self.save_function(props)
  File "/home/user/progs/src/diaphora/diaphora.py", line 574, in save_function
    cur.execute(sql, new_props)
OverflowError: Python int too large to convert to SQLite INTEGER
````

**Comment by joxeankoret** [comment]
And that bug re-appeared again. I don't know how many instances of it I've fixed. Thanks a lot for reporting, I will fix it soon.

PS: If it's possible, it would be cool to have the binary that is triggering this problem, as other bootloaders and kernels I do diff don't trigger it any more since long-long ago.

**Comment by joxeankoret** [comment]
I cannot reproduce it :/ [This check](https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L550) should actually prevent this bug at export time. Can you share binaries or try to debug yourself what property is it failing?

**Comment by joxeankoret** [comment]
Or... wait! Can you test by changing the line I previously mentioned with this:

```      if type(prop) is long and (prop > 0xFFFFFFFF or prop - 0xFFFFFFFF):```

**Comment by gymgit** [comment]
That seems to fix the issue, thank you!

And sorry but I am not allowed to share the binary or the idb.

**Comment by joxeankoret** [comment]
It's ok, no worries. I understand.
