### ISSUE TITLE
Error occour when there are single quotes in names of functions

### ISSUE THREAD

**Issue by b6c** [joxeankoret/diaphora#115]
diaphora.py line 1691, following code can solve the problem.

cur.execute(sql % (("%s of %s/%s" % (call_type, name1, name2)).replace('\\'', '\\'\\''), ",".join(main_address_set), ",".join(diff_address_set)))

**Comment by joxeankoret** [comment]
Oh, really? I introduced a SQL injection... :man_facepalming: Thanks for reporting!

**Comment by joxeankoret** [comment]
Fixed. Thanks for reporting!

**Comment by b6c** [comment]
You are welcome. 
By the way,  diaphora  is a nice tool.

**Comment by joxeankoret** [comment]
Thank you :)
