### ISSUE TITLE
Resuming a failed generation of sqlite db

### ISSUE THREAD

**Issue by h2o64** [joxeankoret/diaphora#116]
Hi,
I'm using diaphora on very big i64 files that I'm working with (~2GB) so the sql database generation is VERY long.
But speed isn't my problem, the problem is that the software uses too much memory and eventually my OS crashes.
It's the 5th night that I'm spending watching the process for hours, and it's the 5th time that the sqlite db got "corrupted" and I need to restart.
My question is : is there a way to "resume" from previously writen stuff ?
Like, the sqlite file is writen to the 29780/43720 function, is it possible to resume this state ?

I tried manipulating the sql databases with sqlite3 but with no luck.

Here is the error message : 
```
[18446743798832168960L, 18446743798832168964L, 18446743798832173056L, 18446743798832173056L]
Error: UNIQUE constraint failed: functions.rva
Traceback (most recent call last):
  File "IDA/diaphora-master\diaphora_ida.py", line 1815, in _diff_or_export
    bd.export()
  File "IDA/diaphora-master\diaphora_ida.py", line 600, in export
    self.do_export()
  File "IDA/diaphora-master\diaphora_ida.py", line 583, in do_export
    self.save_function(props)
  File "IDA/diaphora-master\diaphora.py", line 574, in save_function
    cur.execute(sql, new_props)
IntegrityError: UNIQUE constraint failed: functions.rva
```
Thanks.

PS: I posted a topic on the google groups too (https://groups.google.com/forum/?hl=es#!topic/diaphora/IwfkLyEQ-IE)

**Comment by h2o64** [comment]
Thanks :)

**Comment by joxeankoret** [comment]
Done! Sorry for taking that long. The support was added with this commit: https://github.com/joxeankoret/diaphora/commit/1156ee898dcf39c3a1289092e7402ba0a4c4a997
