### ISSUE TITLE
Optimizations desperately needed

### ISSUE THREAD

**Issue by zXtN8HdC7fiT35qb6TiJeL6srnKi9i** [joxeankoret/diaphora#117]
Hello,

I'm trying to diff two versions of an executable for an Unreal Engine 4 game.

The problem with this is that it takes absolutely *ages* to export the sqlite database for a single binary when there's a lot of functions.

![4ega0u](https://user-images.githubusercontent.com/40258552/41394440-3a5edf7e-6faa-11e8-8119-6f1a848aef7d.png)

This is only for the first version of the binary.

Is this maybe a limitation of the IDA API, or are there optimizations to be had in diaphora?

**Comment by zXtN8HdC7fiT35qb6TiJeL6srnKi9i** [comment]
![0cz3j0](https://user-images.githubusercontent.com/40258552/41399266-22704ca8-6fba-11e8-82d4-ceee3bc324ce.png)
Not exactly improving either.

**Comment by joxeankoret** [comment]
I'm not sure I can do too much here. First of all, it has +158K functions, it will take too long regardless of what we do to analyse and export +158K functions. However, I have some tips to perhaps speed it up a bit:

- Are you using the decompiler? If so, disable that option, that should make it a lot faster.
- Another options is to just export function summaries in opposite of exporting everything.
- Another option could be to just export a range of functions.

These options are mentioned here: https://github.com/joxeankoret/diaphora/wiki/Diaphora-takes-too-long-exporting%21

I have some ideas like trying to use various threads. However, the IDA Python API is not multi-thread safe, or at least it wasn't back in the day, and you can find pretty funny crashes at almost random moments (or it happened to me back in the day).

There is still one more option: I have some changes I haven't yet committed that let you select which functions you want to export or not (as well as how to apply transformations over the generated data). Perhaps that exporting filter scripting thing could work for you in that case?

**Comment by leoetlino** [comment]
I was planning to open an issue to suggest a feature that allows filtering exported functions by their name. In my case, I have two binaries, one stripped and the other with complete symbols, and I *know* both executables share most of the framework/utility code.

Is this something that would be handled by your uncommited changes?

**Comment by joxeankoret** [comment]
Most likely, yes. Basically, it is a scriptable hooks system. The current interface is as follows:

```
class CMyHooks:
  def __init__(self, diaphora_obj):
    """ @diaphora_obj is the CIDABinDiff object being used.
    """
    self.diaphora = diaphora_obj

  def before_export_function(self, ea, func_name):
    """ @ea is the address of the function that is going to be read.    
        Return True for the function to be read, or False to ignore it.
    """
    return True

  def after_export_function(self, d):
    # Apply transformations to any field in the dictionary 'd' and return it
    return d

HOOKS = {"DiaphoraHooks": CMyHooks}
```

You write such a script, select it in the export dialog and for each row you can do whatever you want: accept it, discard it, change whatever was exported (like strings or constants), etc... 

I will do my best to push these changes by next week.

**Comment by joxeankoret** [comment]
Hi guys! Please take a look to the example hooks script I have just added: https://github.com/joxeankoret/diaphora/blob/master/hooks/my_hooks.py

Hopefully, it will solve a lot of problems some reversers are having with big databases.
