### ISSUE TITLE
The ability to import only structures, defines,enums, symbol information etc.

### ISSUE THREAD

**Issue by mspublic** [joxeankoret/diaphora#12]
It would be great to be able to import information such structures, defines,enums, symbol etc from one DB into another without modifying/matching the functions themselves. For example when porting from old DB to new DB functions may be different or not exist but the structures/etc may be the same - so it would be great to be able to import all the other data without having to manually select the functions required. IDA has some of this partially implemented with the header/typdef export/import but it misses most items where as Diaphora seems to pickup all the needed ones.

Thanks again for the awesome work Joxean! Diaphora has been a lifesaver!

**Comment by joxeankoret** [comment]
I will implement this functionality as soon as I have time. Thanks for the kind words :)

**Comment by joxeankoret** [comment]
Sorry for taking that long. Added with commit daacadbae7cda54d1cfa3bb68b8bd0fc552646f6
