### ISSUE TITLE
for-loop never get reached for bb_relations

### ISSUE THREAD

**Issue by huammmm1** [joxeankoret/diaphora#120]
I'm trying to grasp the idea how diaphora calculates strongly_connected_components, and found it utilizes Tarjan's algorithm and requires bb_relations to be filled with succs/preds block address before calling the function strongly_connected_components

And successor/predecessor blocks for one specific basic block is added to bb_relations list using the following for-loops

diaphora_ida.py (starting with line 1539)

for succ_block in block.succs():
  succ_base = succ_block.startEA - image_base
  bb_relations[block_ea].append(succ_base)
  ...................

diaphora_ida.py (starting with line 1553)

for pred_block in block.preds():
  try:
    bb_relations[pred_block.startEA - image_base].append(block.startEA - image_base)
  except KeyError:
    bb_relations[pred_block.startEA - image_base] = [block.startEA - image_base]

I tested several ELF binary files, but in my case, for-loop for pred_block is never entered for all functions and don't understand why. (for-loop for succ_block is entered though)

I use IDA 6.8 version.

**Comment by huammmm1** [comment]
I was trying to understand the code and it looked odd to me (I'm not sure though)
And I haven't seen any visible problem..
Let me open an issue if I notice any problem.

Thank you.

**Comment by joxeankoret** [comment]
Sure, feel free to open an issue if you find any problem! I'm closing it for now (feel free to reopen if you think it's required).
