### ISSUE TITLE
save_function not working on mac ida but works fine on windows

### ISSUE THREAD

**Issue by Cryptiiiic** [joxeankoret/diaphora#121]
`  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/diaphora.py", line 555, in save_function
    cur.execute(sql, new_props)
ProgrammingError: Incorrect number of bindings supplied. The current statement uses 40, and there are 43 supplied.`

I've never been able to get diaphora to work on mac, the first time I tried was back in february. 
My ida version is 7.0.

**Comment by joxeankoret** [comment]
This is odd because the error should be at line 575, not at aline 555: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L575

Can you please verify that you're installing the latest version? Also, I know that people use it regularly in MacOSX so, well, it's supported.

**Comment by Cryptiiiic** [comment]
@joxeankoret Yes I am using the latest.
https://streamable.com/s/96hrs/cbrfub

**Comment by joxeankoret** [comment]
Take a look to the paths and remove diaphora.py from "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/". It's taking an old version of Diaphora that was copied to the IDA's Python directory.

Feel free to reopen if you still have the same problem after removing the Diaphora copy from the IDA's directory.
