### ISSUE TITLE
Generate sqlite database from COFF library?

### ISSUE THREAD

**Issue by user202729** [joxeankoret/diaphora#125]
Visual C++ standard library (or a contains a lot of .lib files, which are libraries of COFF object file (.obj file).
Opening a .lib file with IDA will show a list of .obj file inside the library. IDA cannot open the whole .lib file (as far as I know). Therefore, it's not possible to diff against the whole .lib file instead of each .obj separately (which is time-consuming).
I suggest making it possible.

**Comment by joxeankoret** [comment]
I don't think there anything one can do as IDA, AFAIK, doesn't let you script which .obj file from the .LIB file do you want to open. I think the best would be to create a DLL from the .LIB and use it to diff. You can create such a library with a command like the following one:

```
$ link /DLL /out:out.dll your_lib.lib
```

**Comment by joxeankoret** [comment]
Closing it. Feel free to reopen if you have any new information or any new question regarding this.
