### ISSUE TITLE
Selecting sqlite database issue

### ISSUE THREAD

**Issue by psyfl** [joxeankoret/diaphora#126]
When I click the "..." button to select the .sqlite file to diff against, the Windows file explorer that comes up does not allow me to select a .sqlite file. Instead I have to manually enter the path to the .sqlite file to diff against.

**Comment by joxeankoret** [comment]
I'm afraid there is nothing I can do, as this is how the IDA Python APIs for FileInputs works. There is no way I can set the desired file extension.
