### ISSUE TITLE
Integrate Pigaios in Diaphora

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#127]

**Comment by Halastra** [comment]
I noticed you referenced this in your latest update to the README.
Is this currently being worked on?
Is there any way to contribute to the work on this feature?

**Comment by joxeankoret** [comment]
> Is this currently being worked on?

No, not yet. I'm still finishing the port to Python 3.X first.

> Is there any way to contribute to the work on this feature?

First I need to think about how to integrate both tools. Ideas or tips are very welcome.

**Comment by Halastra** [comment]
> No, not yet. I'm still finishing the port to Python 3.X first.

Is there any way to help with this task?

> First I need to think about how to integrate both tools. Ideas or tips are very welcome.

Unfortunately, I currently lack the familiarity required with `Diaphora` to really come up with anything useful. 
I'll try to catch up on the documentation/internals, but I would appreciate it if you could point me in the right direction. Any information/tips regarding the following will help:

- Current state and main assets:
  - What features/components does `Pigaios` currently share with `Diaphora` (e.g. same sqlite DB, etc.)?
  - Which features/components does `Pigaios` improve on? (e.g. AST extraction, AST-based matching heuristics)
- Main challenges:
  - What currently prevents use of externally-provided pseudocode for `Diapora`'s comparison? (other than `NotImplementedError`)
  - What are the main challenges in making `Diaphora` compare using only pseudo-code (i.e.: without disassembly-based heuristics)?

**Comment by joxeankoret** [comment]
First, Pigaios needs updating and testing. And then... I don't know how to do so just yet.

**Comment by joxeankoret** [comment]
Pigaios is abandoned: it doesn't look like anyone really needs it.
