### ISSUE TITLE
Error: no such table: diff.version

### ISSUE THREAD

**Issue by RetroGameDeveloper** [joxeankoret/diaphora#136]
Using IDA Pro 7.0 on MacOSX Mojave and the latest checkout from github, I want to copy symbols from one executable to the other, it successfully creates the two sqlite database.
But after it has finished it gives the following output in the IDA console:
```
[Wed Nov 21 16:23:37 2018] Loading project specific Python script...
[Wed Nov 21 16:23:37 2018] Creating crash file 
/.wine/drive_c/ultra/USR/SRC/PR/DEMOS/tengine/turoku.sqlite-crash...
[Wed Nov 21 16:27:37 2018] Removing crash file /.wine/drive_c/ultra/USR/SRC/PR/DEMOS/tengine/turoku.sqlite-crash...
[Wed Nov 21 16:27:37 2018] Database exported. Took 240.49801302 seconds
[Wed Nov 21 16:27:37 2018] Error: no such table: diff.version 
```

Here are the two MIPS binaries that I was diffing:
[TwoExecutablesForDiffing.zip](https://github.com/joxeankoret/diaphora/files/2605017/TwoExecutablesForDiffing.zip)

**Comment by joxeankoret** [comment]
Let me take a look but... Are you using Wine to run IDA?

**Comment by joxeankoret** [comment]
Usually that error happens because of different (and old) version of Diaphora. Please try re-exporting again the old databases.
