### ISSUE TITLE
UI Feature: Numerical instead of alphabetical ordering when ordering by basic blocks number

### ISSUE THREAD

**Issue by enovella** [joxeankoret/diaphora#137]
Hi all,

**Why**
It would be more useful changing the ordering criteria for basic block columns. Instead of alphabetical to numerical. In this way, you can get insight on how big the function is and order & compare by nr_basicblocks.

**Issue**
![diaphora-issue](https://user-images.githubusercontent.com/14809754/49701890-d0924a00-fbe9-11e8-9021-40c2e59e380f.png)

**Solution**
I might have some time this Christmas so you can assign me the task. I shouldn't be too complex to include this feature. The fix should order `BBlocks1` and `BBlocks2`  columns as the `Ratio` column.

Best

**Comment by joxeankoret** [comment]
There is a workaround but I don't like it: padding to the left with the zeros both columns (as I do with the "Line" column).

I personally don't like doing so but, as you folks wish. What do you think? Should I do it?

**Comment by joxeankoret** [comment]
Closing for now until more people ask for the feature (as I don't know how to make not annoying or configurable without adding even more options to the GUI dialogue).

**Comment by enovella** [comment]
Ok fair enough. Not really a massive improvement so its okay to me as well.
