### ISSUE TITLE
Feature request: Open a diff database

### ISSUE THREAD

**Issue by forker11234** [joxeankoret/diaphora#147]
Hey,
I read this page: https://github.com/joxeankoret/diaphora/wiki/How-can-I-automate-the-diffing-process%3F
I wanted to know if it is possible to read the diff database via IDA and not through sql queries.
If It's not possible it will be a great feature to add!

**Comment by forker11234** [comment]
Realised that it can be done by diaphoa_load.py script :>

**Comment by joxeankoret** [comment]
OK :)
