### ISSUE TITLE
Diff pseudo-code widget displays code incorrectly

### ISSUE THREAD

**Issue by shuffle2** [joxeankoret/diaphora#152]
There seems to be at least two issues:

1.  There is a line-width cutoff (after some number of columns, text is not printed anymore
![image](https://user-images.githubusercontent.com/113063/52528602-8c79ff00-2c97-11e9-9df1-fcb59487347d.png)

1. Certain character sequences cause the output to be elided/wrong
![image](https://user-images.githubusercontent.com/113063/52528587-49b82700-2c97-11e9-9380-b8673afa58a9.png)
becomes
![image](https://user-images.githubusercontent.com/113063/52528590-576dac80-2c97-11e9-9320-ac2c890fc7e6.png)

**Comment by joxeankoret** [comment]
Oops! I don't really know how to fix the 1st issue but I can fix the 2nd issue easily. Working on a fix.

PS: If any of you folks happen to know any way I could fix the line-width cutoff, help would be highly appreciated.

**Comment by joxeankoret** [comment]
Please give me some example binaries to test it because it doesn't always reproduce (the 2nd behaviour). Or, alternatively, try yourself this patch:

```diff
diff --git a/diaphora_ida.py b/diaphora_ida.py
index ee49b88..4ca8161 100644
--- a/diaphora_ida.py
+++ b/diaphora_ida.py
@@ -2261,6 +2261,12 @@ class CHtmlDiff:
         rtxt = self._stop_wasting_space(rtxt)
         ltxt = self._trunc(ltxt, changed).replace(" ", "&nbsp;")
         rtxt = self._trunc(rtxt, changed).replace(" ", "&nbsp;")
+        
+        ltxt = ltxt.replace("<", "&lt;")
+        ltxt = ltxt.replace(">", "&gt;")
+        rtxt = rtxt.replace("<", "&lt;")
+        rtxt = rtxt.replace(">", "&gt;")
+
         row = self._row_template % (str(lno), ltxt, str(rno), rtxt)
         rows.append(row)
```

**Comment by shuffle2** [comment]
The binaries were most recent mIRC compared to previous, I dont have the binaries/idbs/sqldb around anymore....may or may not get around to trying it out...

**Comment by joxeankoret** [comment]
I have partially fixed this, but I haven't been able to do anything with the line-width cutoff! If somebody knows what could I do with this, I would be thankful.

**Comment by joxeankoret** [comment]
Finally fixed!
