### ISSUE TITLE
Incorrect data renaming behavior on ARM

### ISSUE THREAD

**Issue by flowswitch** [joxeankoret/diaphora#154]
Identified data items referenced by PC-relative pools  (LDR Rx, =SomeVar) are handled incorrectly. Instead of renaming the data item itself Diaphora renames the pointer storage address in the pool.
Example:
```
SomeIdentifiedSub:
   LDR R0, =SomeIdentifiedVar ; this is LDR R0, [PC, OffsetOfPtrInPool]
   ...
PtrInPool: DCD SomeIdentifiedVar
```
SomeIdentifiedVar will not be renamed, PtrInPool will be renamed instead.

**Comment by joxeankoret** [comment]
Can you share some binary so I can reproduce this exact behaviour?

**Comment by flowswitch** [comment]
Here is it, among with a readme.txt instruction to reproduce the behavior:
[DiaphoraTestArm.zip](https://github.com/joxeankoret/diaphora/files/2985995/DiaphoraTestArm.zip)

**Comment by joxeankoret** [comment]
First of all, thank you very much for such detailed instructions! I can reproduce it and I'm working on a fix.

**Comment by joxeankoret** [comment]
Fixed!
