### ISSUE TITLE
Automatic diffing fails (fix included)

### ISSUE THREAD

**Issue by boredpentester** [joxeankoret/diaphora#156]
Diaphora fails to diff two valid databases when ran from the command line.

Ran via:
> set DIAPHORA_AUTO_DIFF=1
> set DIAPHORA_AUTO=1
> set DIAPHORA_DIFF_OUT=Y:\tools\xxxx\out.diaphora
> set DIAPHORA_DB1=Y:\tools\xxxx\diphora_primary.sqlite
> set DIAPHORA_DB2=Y:\tools\xxxx\diphora_secondary.sqlite
> 
> @echo "Diaphora harness (DIFF RESULT WRAPPER) V1.0"
> @echo "Diffing DBs!"
> python C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py

Output:
> [Fri Feb 22 16:56:25 2019] Diffing...
> 
> [Fri Feb 22 16:56:28 2019] Callgraphs from both programs differ in 95.206136%
> 
> [Fri Feb 22 16:56:28 2019] Finding best matches...
> 
> [Fri Feb 22 16:56:30 2019] [Parallel] Finding with heuristic 'Same RVA and hash'
> 
> 
> [Fri Feb 22 16:56:30 2019] [Parallel] Finding with heuristic 'Same order and hash'
> 
> [Fri Feb 22 16:56:30 2019] [Parallel] Finding with heuristic 'Function Hash'
> 
> Traceback (most recent call last):
>  File "C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py", line 2657, in <module>
>  bd.diff(db2)
>  File "C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py", line 2586, in diff
>   self.find_equal_matches_parallel()
>  File "C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py", line 1008, in find_equal
>_matches_parallel
>    self.run_heuristics_for_category("Best")
>  File "C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py", line 1084, in run_heuris
>tics_for_category
>    log_refresh("[Parallel] %d thread(s) running, waiting for at least one to fi
>nish..." % len(threads_list), do_log=False)
>TypeError: log_refresh() got an unexpected keyword argument 'do_log'

Patching away the "do_log" parameters passed to log_refresh() and re-trying:
>[Fri Feb 22 16:58:27 2019] Diffing...
>
>[Fri Feb 22 16:58:29 2019] Callgraphs from both programs differ in 95.206136%
>
>[Fri Feb 22 16:58:29 2019] Finding best matches...
>
>[Fri Feb 22 16:58:30 2019] [Parallel] Finding with heuristic 'Same RVA and hash
>
>
>[Fri Feb 22 16:58:30 2019] [Parallel] Finding with heuristic 'Same order and hah'
>
>[Fri Feb 22 16:58:30 2019] [Parallel] Finding with heuristic 'Function Hash'
>
>[Fri Feb 22 16:58:30 2019] [Parallel] 3 thread(s) running, waiting for at least
>one to finish...
>
>Traceback (most recent call last):
>  File "C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py", line 2657, in <module>
>    bd.diff(db2)
>  File "C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py", line 2586, in diff
>    self.find_equal_matches_parallel()
>  File "C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py", line 1008, in find_equa
>_matches_parallel
>    self.run_heuristics_for_category("Best")
>  File "C:\Users\xxxx\Desktop\RE\diaphora\diaphora.py", line 1086, in run_heuri
>tics_for_category
>    idaapi.request_refresh(0xFFFFFFFF)
>NameError: global name 'idaapi' is not defined

Adding check to make sure IDA API isn't used when not using IDA:

> if(is_ida):
>              idaapi.request_refresh(0xFFFFFFFF)

Results in a valid diff result and working as expected :).

OS details:

* OS: Windows 7 64-bit Pro SP1
* CPU: Intel Core I7
* Architecture: VirtualBox VM
* Memory: 12GB
* Python: 2.7.9

**Comment by joxeankoret** [comment]
Agh... I broke it. Thanks for reporting!

**Comment by joxeankoret** [comment]
Fixed with the latest commit. Thanks for reporting!
