### ISSUE TITLE
Add Support for Iterative Analysis

### ISSUE THREAD

**Issue by AshKetch-um** [joxeankoret/diaphora#158]
During analysis for partial/unreliable matches, if a function is incorrectly matched, it can have a cascading effect on other matches (or lack thereof) due to their incorrect relationships (e.g. through Import Names Hash and KOKA heuristics). One particularly effective solution to this with BinDiff was to perform iterative analysis. This allowed you to "accept matches" after a given pass and then feed in the accepted matches as perfect matches into the next iteration of differential analysis with the chance of it improving the results.

Please consider adding support for iterative analysis.

(Note: I'm unsure if this is related to Issue #144 or not)

**Comment by joxeankoret** [comment]
Yes, it's related to #144 but I didn't have a proper example so, thanks for giving me one :)

**Comment by joxeankoret** [comment]
Adding manual matches is already implemented in Diaphora 2.0.

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum

**Comment by misc544** [comment]
Ash Ketchum
