### ISSUE TITLE
How to set diff settings when batch diffing?

### ISSUE THREAD

**Issue by conioh** [joxeankoret/diaphora#160]
Let's say I've exported two sqlite files using IDA and Diaphora and want to diff them (perhaps on a computer without IDA installed at all) as described on the wiki page _[How can I automate the diffing process?](https://github.com/joxeankoret/diaphora/wiki/How-can-I-automate-the-diffing-process%3F)_

The page just says how to pass the two input files and the name for the output file. Is there a way to set things like _use probably unreliable methods_, _use slow heuristics_, etc.?

**Comment by joxeankoret** [comment]
Uhm... no, there is no way because nobody asked for it. Until now. Give me a couple of days.

**Comment by conioh** [comment]
Thanks. I'll hijack my own issue to also ask: When using batch compare which argument is considered the "primary" ("new") and which the "secondary" ("old")? Does it matter?

**Comment by joxeankoret** [comment]
Old one is first, second one is the new. Sorry for taking a bit longer than expected, I will need some more days to implement the feature.

**Comment by conioh** [comment]
> Old one is first, second one is the new. 

I somehow guessed it was the other way around. At the end of `diaphora.py` I see:

    bd = CBinDiff(db1)
    bd.db = sqlite3.connect(db1, check_same_thread=True)
    bd.db.text_factory = str
    bd.db.row_factory = sqlite3.Row
    bd.diff(db2)
    bd.save_results(diff_out)

where `db1` and `db2` are the args in the order they were given.

In `diaphora_ida.py` I see in `CBinDiffExporterSetup`'s constructor that `iFileSave` is the path to the new db and `iFileOpen` is the path to the old one. Thet later become `opts.file_out` and `opts_file_in` and use [like this for example](https://github.com/joxeankoret/diaphora/blob/master/diaphora_ida.py#L2160):

    bd.diff(opts.file_in)

So it looks like `db2` in the batch compare is parallel to `opts.file_in` when running from IDA, and `opts.file_in` is the "old file" we choose is in the GUI. What am I missing?



> Sorry for taking a bit longer than expected, I will need some more days to implement the feature.

No worries. and thanks again. :)

In the meanwhile I hard-coded a couple parameters I want in the script :)

Does it make sense perhaps to also allow setting `MAX_PROCESSED_ROWS` and `TIMEOUT_LIMIT` by the user? With a big enough binary and a big enough IDB and SQLite DB perhaps the preset limits are too narrow?

**Comment by joxeankoret** [comment]
I've just added support for handling MAX_PROCESSED_ROWS and TIMEOUT_LIMIT: https://github.com/joxeankoret/diaphora/commit/9c08ad8d445c710fd10912e340e2f81c626f6217

Now working on how to expose the other options to batch processing.

**Comment by joxeankoret** [comment]
And done! I have added a few new environment variables for both batch diffing and exporting:

- DIAPHORA_UNRELIABLE
- DIAPHORA_RELAXED_RATIO
- DIAPHORA_EXPERIMENTAL
- DIAPHORA_SLOW_HEURISTICS
- DIAPHORA_IGNORE_ALL_NAMES
- DIAPHORA_IGNORE_SMALL_FUNCTIONS
- DIAPHORA_EXCLUDE_LIBRARY_THUNK
- DIAPHORA_IDA_SUBS
- DIAPHORA_IGNORE_SUB_NAMES
- DIAPHORA_FUNCTION_SUMMARIES_ONLY
