### ISSUE TITLE
Control temp files path

### ISSUE THREAD

**Issue by conioh** [joxeankoret/diaphora#161]
It might be very useful to be able to control the location of the temporary files created during the diff.

Currently I'm looking at:
![image](https://user-images.githubusercontent.com/10606081/56325729-e9080780-617b-11e9-8ab1-8406422f963c.png)

The multi-GB-big `.idb`s and `.sqlite`s are on `D:`, but unfortunately the 22GB (so far) temp file is on the `C:` drive. I don't think it's going to end well. 😟 In the minute I wrote this post free space went down from 4.19GB to 3.57GB.

It would be very useful if I could control the location of the temp file, or, alternatively, if it would be created in the same location as the output file.

**Comment by conioh** [comment]
As expected:

```
Traceback (most recent call last):
  File "d:\Diaphora\diaphora.py", line 2664, in <module>
    bd.diff(db2)
  File "d:\Diaphora\diaphora.py", line 2602, in diff
    self.find_callgraph_matches()
  File "d:\Diaphora\diaphora.py", line 1832, in find_callgraph_matches
    self.find_callgraph_matches_from(best_items, 0.60)
  File "d:\Diaphora\diaphora.py", line 1903, in find_callgraph_matches_from
    cur.execute(sql % (("%s of %s/%s" % (call_type, tname1, tname2)), ",".join(main_address_set), ",".join(diff_address_set)))
sqlite3.OperationalError: database or disk is full
```

😞

**Comment by joxeankoret** [comment]
By default SQLite temporary files are left in the same directory as the IDB you are exporting. I will add to my TODO list, it will probably be just an environment variable (I will implement as soon as I finish some slides for an upcoming conference).

BTW, this is what we're interested on: https://www.sqlite.org/pragma.html#pragma_temp_store_directory

**Comment by conioh** [comment]
> By default SQLite temporary files are left in the same directory as the IDB you are exporting. I will add to my TODO list, it will probably be just an environment variable (I will implement as soon as I finish some slides for an upcoming conference).
> 
> BTW, this is what we're interested on: https://www.sqlite.org/tempfiles.html

The `-journal` files are kept next the database file themselves but the `etilqs` files are stores in `%TMP%, and those are the huge files I noticed. Changing %TMP% helped. Thanks to the link you provided we see that this is indeed the expected behavior:

> On Windows systems, folders are searched in the following order:
> 
> 1. The folder set by PRAGMA temp_store_directory or by the sqlite3_temp_directory global variable
> 2. The folder returned by the GetTempPath() system interface.
>
> SQLite itself does not pay any attention to environment variables in this case, though presumably the GetTempPath() system call does.

And [`GetTempPath`](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-gettemppathw) returns the value of `%TMP%` if it exists.

We can't set the global variables since we don't want to build sqlite ourselves. Seems like checking the OS (Windows or *NIX) and setting the appropriate environment variable (`TMP` for Windows, `SQLITE_TMPDIR` for *NIX) _before_ initializing SQLite should work though.

**Comment by joxeankoret** [comment]
I don't think I should add the environment variable myself in diaphora.py. Indeed, I believe that I just need to document that $TMP is the environment variable that controls this. Thanks for the research you did!
