### ISSUE TITLE
Can I compare only partial functions?

### ISSUE THREAD

**Issue by kiritowch** [joxeankoret/diaphora#162]
I need to compare a lot of firmware functions. Can I use a script or some setting in diaphora to specify the address/name of the function to be compared and let diaphora compare only those specific functions?

**Comment by joxeankoret** [comment]
Yes, you can. You can do it in 2 ways:

1. Specify an address range in the GUI (from 0xSOMETHING to 0xSOMETHINGELSE).
2. Use a hooks script like this one: https://github.com/joxeankoret/diaphora/blob/master/hooks/my_hooks.py

It seems that what you need is the option 2. From the example script here https://github.com/joxeankoret/diaphora/blob/master/hooks/my_hooks.py#L32, what you need to do is to modify this method:

```python

  def before_export_function(self, ea, func_name):
    """ @ea is the address of the function that is going to be read.    
        Return True for the function to be read, or False to ignore it.
    """

    # If the IDB name has the word 'user' on it, it's the user-land database for
    # which we want to export everything.
    if self.db_name.find("user") > -1:
      return True

    # Otherwise, it's the kernel-land IDB for which we only want to export the
    # syscall functions.
    if func_name:
      # Is it a syscall?
      for prefix in FUNC_PREFIXES:
        if func_name.startswith(prefix):
          return True

return False```

This method must return True for functions that you want to export or False for those that you want to ignore.

Did I answer your question?

**Comment by kiritowch** [comment]
Ok, I will try it later, it should be ok, thank you very much!
