### ISSUE TITLE
Why not import to IDA7.0？

### ISSUE THREAD

**Issue by 321816401** [joxeankoret/diaphora#164]
error：No IDA database opend or no function in the database. Please open an IDA database and create some functions before running this script

**Comment by joxeankoret** [comment]
I think it's pretty self-explanatory: open the database of the file to be exported and/or diffed first.

**Comment by 321816401** [comment]
i'm talking about the "script file".i installed it according to the documentation,but it prompts：“No IDA database opend or no function in the database. Please open an IDA database and create some functions before running this script”

**Comment by joxeankoret** [comment]
You will have to explain yourself better. Are you opening some binary in IDA before running the Python script diaphora.py or diaphora_ida.py?

**Comment by 321816401** [comment]
i sent pictures to your Facebook,please check it out......

**Comment by joxeankoret** [comment]
Sorry, but I cannot find anything sent to my Facebook. You can put images in Github or, alternatively, you can send me an e-mail to joxean.piti AT gmail DOT com.

**Comment by 321816401** [comment]
i have sent an email to you. my e-mial name is troshintt AT gmail DOT com...thank you

**Comment by joxeankoret** [comment]
Explained via e-mail.
