### ISSUE TITLE
Invalid download link on homepage

### ISSUE THREAD

**Issue by exscape** [joxeankoret/diaphora#169]
diaphora.re has a link to https://github.com/joxeankoret/diaphora/zipball/gh-pages .

When you download the linked file, you get (as the URL suggests) some web stuff. CSS, some images, some JavaScript. The same should apply to the .tar.gz file.

The intended link may be https://github.com/joxeankoret/diaphora/archive/master.zip instead.

**Comment by joxeankoret** [comment]
Yep. It's a known issue but I don't really know how to fix. I will take a look today.

**Comment by joxeankoret** [comment]
Kind of fixed by just removing the links.
