### ISSUE TITLE
Suppress "Decompiling..." message box

### ISSUE THREAD

**Issue by patois** [joxeankoret/diaphora#170]
Starting with IDA 7.3 (or so I believe), ida_hexrays.decompile() accepts a flags argument, such as "DECOMP_NO_WAIT". If this argument is specified, the "Decompiling..."  "wait box" is suppressed. Among other things, this should be much more pleasant to the eyes :)

**Comment by joxeankoret** [comment]
I didn't know such a flag was added. Thanks!

**Comment by joxeankoret** [comment]
Done. Fixed with 40807646f6fb6023cc67c1646b8376c12c1ad752. Thanks!
