### ISSUE TITLE
DLL load failure

### ISSUE THREAD

**Issue by s3c** [joxeankoret/diaphora#173]
I'm using IDA 7.4 and Python 3.75. When loading the script I get the following error message:

```
C:\Tools\diaphora-2.0\diaphora.py: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_idaapi.py", line 590, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Tools/diaphora-2.0/diaphora.py", line 2010, in <module>
    exec(compile(open(script, "rb").read(), script, 'exec'))
  File "C:/Tools/diaphora-2.0\diaphora_ida.py", line 46, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.
```

I've confirmed that the PyQt5 import line works in an interactive Python console, but not when loaded by IDA. Any ideas?

**Comment by joxeankoret** [comment]
Please run in the IDA python prompt (with an opened database) the following line:

```
>>> from PyQt5 import QtCore, QtGui, QtWidgets
```

If it doesn't work, it smells like an IDA Python specific problem. If so, run in a terminal the following command:

```
$ $IDA74_DIR/idapyswitch
```

**Comment by s3c** [comment]
Thanks, idapyswitch fixed the problem.

**Comment by joxeankoret** [comment]
You're welcome!

**Comment by s3c** [comment]
Note for future reference, run idapyswitch as in elevated context.

**Comment by BigCatGit** [comment]
> I'm using IDA 7.4 and Python 3.75. When loading the script I get the following error message:
> 
> ```
> C:\Tools\diaphora-2.0\diaphora.py: DLL load failed: The specified module could not be found.
> Traceback (most recent call last):
>   File "C:\Program Files\IDA Pro 7.4\python\3\ida_idaapi.py", line 590, in IDAPython_ExecScript
>     exec(code, g)
>   File "C:/Tools/diaphora-2.0/diaphora.py", line 2010, in <module>
>     exec(compile(open(script, "rb").read(), script, 'exec'))
>   File "C:/Tools/diaphora-2.0\diaphora_ida.py", line 46, in <module>
>     from PyQt5 import QtCore, QtGui, QtWidgets
> ImportError: DLL load failed: The specified module could not be found.
> ```
> 
> I've confirmed that the PyQt5 import line works in an interactive Python console, but not when loaded by IDA. Any ideas?
