### ISSUE TITLE
Can diaphora used to compare the similarity of two executable files?

### ISSUE THREAD

**Issue by rainkin1993** [joxeankoret/diaphora#174]
Hi,

Thanks for the great tool.

I want to compare the code similarity of two executable files. That is, the input is two files, the output is the similarity percentage. 

Does diaphora support this function? or Do you have any suggestions that I can modify diaphora to get this function work? or do you know any other tools which can perform this function? 

Thanks very much

**Comment by joxeankoret** [comment]
When you diff 2 binaries Diaphora says, comparing the call graphs, how different or similar are them. For example, diffing 2 different versions of the Ubuntu's 'ls' binary, it will say something like this:

```
[Thu Oct 24 17:16:04 2019] Diffing...
[Thu Oct 24 17:16:04 2019] Callgraphs from both programs differ in 28.712871%
```

The whole Python code for doing this is the following one:

```
  def check_callgraph(self):
    cur = self.db_cursor()
    sql = """select callgraph_primes, callgraph_all_primes from program
             union all
             select callgraph_primes, callgraph_all_primes from diff.program"""
    cur.execute(sql)
    rows = cur.fetchall()
    if len(rows) == 2:
      cg1 = decimal.Decimal(rows[0]["callgraph_primes"])
      cg_factors1 = json.loads(rows[0]["callgraph_all_primes"])
      cg2 = decimal.Decimal(rows[1]["callgraph_primes"])
      cg_factors2 = json.loads(rows[1]["callgraph_all_primes"])

      if cg1 == cg2:
        self.equal_callgraph = True
        log("Callgraph signature for both databases is equal, the programs seem to be 100% equal structurally")
        Warning("Callgraph signature for both databases is equal, the programs seem to be 100% equal structurally")
      else:
        FACTORS_CACHE[cg1] = cg_factors1
        FACTORS_CACHE[cg2] = cg_factors2
        diff = difference(cg1, cg2)
        total = sum(cg_factors1.values())
        if total == 0 or diff == 0:
          log("Callgraphs are 100% equal")
        else:
          percent = diff * 100. / total
          if percent >= 100:
            log("Callgraphs are absolutely different")
          else:
            log("Callgraphs from both programs differ in %f%%" % percent)

    cur.close()
```

So, basically, after exporting 2 binaries with Diaphora, you can open the .sqlite database, select the fields ```callgraph_primes``` and ```callgraph_all_primes``` and, then, factor them using the function ```difference``` in the file jkutils.difference, if you want. It will calculate how many functions are different, regardless of functions being re-arranged or not.

Does this answer your question?

**Comment by rainkin1993** [comment]
That really helps me. Thanks.

**Comment by joxeankoret** [comment]
You're welcome :)
