### ISSUE TITLE
Several minor issues

### ISSUE THREAD

**Issue by expend20** [joxeankoret/diaphora#176]
Hi, maybe I'm doing something wrong, pls correct me if so. 

I've tried to use last version of diaphora from git to create database for gdiplus.dll (32bit). It stuck on next lines which I corrected:

```diff
@@ -1660,7 +1661,8 @@ or selecting Edit -> Plugins -> Diaphora - Show results""")
           continue

         bytes_hash.append(curr_bytes)
-        bytes_sum += sum(curr_bytes)
+        # bytes_sum += sum(curr_bytes) # TypeError: unsupported operand type(s) for +: 'int' and 'str'
+        bytes_sum += sum(bytearray(curr_bytes))
``` 

After that it stuck on the mistake when `mnemonics_spp` in `read_function` was too huge (like this `9046725931316725110106007574107697179936603627950026803262809546491690059838992220716280290325022465098852754794149146040154088070761709815681287389351847709L`), which I quickly patched to overcome this:

```diff
@@ -1622,6 +1622,7 @@ or selecting Edit -> Plugins -> Diaphora - Show results""")

         if mnem in cpu_ins_list:
           mnemonics_spp *= self.primes[cpu_ins_list.index(mnem)]
+          mnemonics_spp &= 0xffffffff # Python int too large to convert to SQLite INTEGER
```

And then I hit and corrected next issue:

```diff
@@ -631,7 +631,8 @@ class CBinDiff:
       if type(prop) is int and (prop > 0xFFFFFFFF or prop < -0xFFFFFFFF):
         prop = str(prop)
       elif type(prop) is bytes:
-        prop = prop.encode("utf-8")
+        #prop = prop.encode("utf-8") # UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 2622: ordinal not in range(128)
+        prop = prop.decode('unicode_escape')

```

But in the end I just got a lot of "Error getting assembly for 0x" errors. All of this seems kind of weird to me, any ideas?

PS: I've also tried tags: 2.0, 2.0.1, 2.0.2, it seems they all have the first mentioned issue in this ticket.
Tag 1.2.4 seems ok to me.

Thanks)

**Comment by kuqadk3** [comment]
Maybe we should save the mnemonics_spp as a string after it got calculated.

**Comment by kuqadk3** [comment]
https://github.com/joxeankoret/diaphora/blob/be4deb38304f25c42b583fecc2369a2aa84728e6/diaphora.py#L359

mnemonics_spp is saved as text in Sqlite db so I don't think you have to limit it to 0xffffffff at all.

**Comment by joxeankoret** [comment]
Hi @expend20 : please share the hash of your specific GdiPlus DLL, as I have exported with no problem at all a version of GdiPlus.DLL from Win10 (but for x64), because the problems you mention are really weird and do not make sense to me at all :?

**Comment by expend20** [comment]
Which hash? I can give you the binary, [here you are](https://minio.tw1st.link/dump/temp/GdiPlus.dll?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NvaiSdSmTMFC0GmszEnE%2F20200120%2F%2Fs3%2Faws4_request&X-Amz-Date=20200120T100339Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=7640d8afad8e9328f925fee107c9fca6c67a815e3f08c7ddabe51bfd382e088a).

```
[Mon Jan 20 12:02:43 2020] Loading project specific Python script...
[Mon Jan 20 12:02:43 2020] Creating crash file c:\s\tmp\GdiPlus.dll.sqlite-crash...
Error: unsupported operand type(s) for +: 'int' and 'str'
Traceback (most recent call last):
  File "c:/s/git/diaphora2\diaphora_ida.py", line 2260, in _diff_or_export
    bd.export()
  File "c:/s/git/diaphora2\diaphora_ida.py", line 819, in export
    self.do_export(crashed_before)
  File "c:/s/git/diaphora2\diaphora_ida.py", line 773, in do_export
    props = self.read_function(func)
  File "c:/s/git/diaphora2\diaphora_ida.py", line 1644, in read_function
    bytes_sum += sum(curr_bytes)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by joxeankoret** [comment]
I cannot reproduce the issue but I think I know what's happening. Are you using IDA 7.4 with Python 2.X, maybe? If so, please try with Python 3.X, as Diaphora doesn't support Python 2.X any more. If this isn't the case, please tell.

**Comment by expend20** [comment]
Yeah, that was exactly the issue, thanks a lot!

**Comment by joxeankoret** [comment]
You're welcome!
