### ISSUE TITLE
Diaphora overlooked valued patch

### ISSUE THREAD

**Issue by expend20** [joxeankoret/diaphora#178]
Hi! 
Once again, I may misunderstand something. So, let me apologize in advance if so :)

I diffed two files and Diaphora showed no "Partial matches" tab, which means that there was no differences, right? But if you pay close attention to one of the functions with 1.0 rating:

![image](https://user-images.githubusercontent.com/36543551/72741016-7830c880-3baf-11ea-9740-0a90eca5d456.png)

you can find differences:

![image](https://user-images.githubusercontent.com/36543551/72741063-90a0e300-3baf-11ea-8be1-a93a617ecf83.png)

My question is why that function has 1.0 rating?

Thanks)

**Comment by kuqadk3** [comment]
It seems like those two functions were matched base on a heuristic "Bytes hash and name" which match those functions by their name and md5(all_bytes). You can check if all bytes in those two functions are the same or not (since IDA spit out that result so it's highly likely the same). If so, I think it's because of the decompiler.

**Comment by expend20** [comment]
Bytes are different, hence md5 is not matched. Here are the binaries [1](https://minio.tw1st.link/dump/temp/GdiPlus.dll?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NvaiSdSmTMFC0GmszEnE%2F20200120%2F%2Fs3%2Faws4_request&X-Amz-Date=20200120T181237Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=ba02d042152bc0220691bbe23e814836b474119b1edf10bdf94f566e8b14fa7f) and [2](https://minio.tw1st.link/dump/temp/GdiPlus_0.dll?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NvaiSdSmTMFC0GmszEnE%2F20200120%2F%2Fs3%2Faws4_request&X-Amz-Date=20200120T181308Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=86af60acd0123317c7c9200e4380908626dcc5573f66b06fe8933bb1e4c0825d)

![image](https://user-images.githubusercontent.com/36543551/72749158-ea120d80-3bc1-11ea-93fa-285ef0141bb9.png)

**Comment by expend20** [comment]
PS: I was using Diaphora 2.0.2

**Comment by joxeankoret** [comment]
It might be a bug. Can you share the other binary you're trying to diff against?

**Comment by expend20** [comment]
I've shared them, pls check

> Here are the binaries [1](https://minio.tw1st.link/dump/temp/GdiPlus.dll?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NvaiSdSmTMFC0GmszEnE%2F20200120%2F%2Fs3%2Faws4_request&X-Amz-Date=20200120T181237Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=ba02d042152bc0220691bbe23e814836b474119b1edf10bdf94f566e8b14fa7f) and [2](https://minio.tw1st.link/dump/temp/GdiPlus_0.dll?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NvaiSdSmTMFC0GmszEnE%2F20200120%2F%2Fs3%2Faws4_request&X-Amz-Date=20200120T181308Z&X-Amz-Expires=432000&X-Amz-SignedHeaders=host&X-Amz-Signature=86af60acd0123317c7c9200e4380908626dcc5573f66b06fe8933bb1e4c0825d)

**Comment by joxeankoret** [comment]
Oh, sorry, I missed that. Looking into it...

**Comment by joxeankoret** [comment]
And, indeed, it was a bug. Thank you very much for reporting! Fixed with commit 44dfc7d31401f94764f1f62f2de626527c7fb29c

**Comment by expend20** [comment]
Thanks a lot for an amazing tool and quick fix!

**Comment by joxeankoret** [comment]
You're very welcome!
