### ISSUE TITLE
Potential issue: row_is_importable may not be checking names

### ISSUE THREAD

**Issue by syntroniks** [joxeankoret/diaphora#179]
https://github.com/joxeankoret/diaphora/blob/44dfc7d31401f94764f1f62f2de626527c7fb29c/diaphora_ida.py#L1185-L1191

Some things that should be importable are not being marked as so.
I believe the line should be 
```    # Has a name
    if import_syms[ea][3] is not None:
      return True
```

**Comment by joxeankoret** [comment]
That's 100% sure a bug. Thanks for reporting this...

**Comment by joxeankoret** [comment]
Sorry for taking so long, the bug should be fixed now.
