### ISSUE TITLE
filter/remove low-complexity matches

### ISSUE THREAD

**Issue by shuffle2** [joxeankoret/diaphora#18]
I am using diaphora with some c/c++ arm code.  
The binary is a large image consisting of multiple modules, each having been statically compiled against some standard library (memcpy, strlcat, etc). I have different major+minor versions of this image.  
So I am using diaphora to:
 * import names into a new version
 * propogate names between individual modules in the image  

In order to do this, I starting making diaphora scriptable: https://github.com/shuffle2/diaphora/commit/68d4f16e973c199a70ed4d3d7b50881bde43c90d
So far it works-ish for my purposes, but needs improvement to be used in a fully programmatic (no user intervention) manner.  

Anyways, I have noticed:
 * diaphora sometimes displays the "unreliable" results when I do not want to see them.
 * there are often many matches detected which are basically nullsubs, return-constant functions, thunks to other functions, etc. It would be very handy if there were a way to separate or remove these kind of resutls.

**Comment by joxeankoret** [comment]
Hi,

Please send me a pull request with your patch, I will apply it. As for the other problems you mention, I will take a look today to see how can I fix it. The thunks, nullsubs, etc... can be a bit annoying, I agree.

**Comment by joxeankoret** [comment]
Added support for ignoring small functions with commit 054318c4e2aaf2590c676096f434e3b5fc6a8e9a
