### ISSUE TITLE
Diff 2 sqlite databases, without analyzing the first one again

### ISSUE THREAD

**Issue by knutwurst** [joxeankoret/diaphora#182]
I am using IDA 7 Pro with Diaphora and as far as I can see, there is no option to  diff two already existing databases. Or am I missing something? 

I try to analyze two 80MB exe files, which takes a lot of time (around 4 hours each on my machine) and I'd like to save some time ;)

Best regards!

**Comment by expend20** [comment]
Hi, just use the same dialog, it will realize that db is already created and ask you to reuse it. You can either accept it (this is what you need) or re-create it.

**Comment by knutwurst** [comment]
It asks me to overwrite the existing database and starts analyzing again.... wait a sec... Oh! I need to click "NO" to start diffing! That's a bit counterintuitive, but yes, that's the trick. Thank you very much!

**Comment by joxeankoret** [comment]
If you have any idea to make it more intuitive, I'm all ears.

**Comment by knutwurst** [comment]
> If you have any idea to make it more intuitive, I'm all ears.

Maybe a dialog, which tells something like: "There already exists a database with the size of xxx GB, would you like to use it, or do you want to create a new one and overwrite the existing? [Use existing] [Overwrite]"

Also the first Dialog, which pops up, could be more explicit. Like an "create sqlite database" procedure and an explicit sqlite-compare-procedure.

Also it would be nice to have a dialog to configure the timeouts.

I also did it yesterday (took about 5 hours and used 600GB of space!), but now, I've got a 65MB *.diaphora file. I'm so happy with it. It's really a great tool and the possibility to diff with pseudocode is the best thing i've ever seen! Thank you so much!
