### ISSUE TITLE
Error ! dividing by zero

### ISSUE THREAD

**Issue by paramikoooo** [joxeankoret/diaphora#184]
Ida 6.6
log :
Python 2.7.2
IdaPython v1.7.0
Error:integer division or modulo by zero
Traceback (most recent call last):
File<diaphora.py path> line 3711 in _diff_or_export
bd.export()
File <diaphora.py path> line 1519 in export
self.do_export()
File <diaphora.py path> line 1508 in do_export
if i % (total_func/10) == 0:
ZeroDivisionError: integer division or modulo by zero

I don't know how to check my diaphora version, but diaphora.py is 139837 bytes.

**Comment by joxeankoret** [comment]
I am afraid I do not support IDA 6.6 since looooong ago. Sorry.
