### ISSUE TITLE
diaphora crashed  Ida 7.4

### ISSUE THREAD

**Issue by paramikoooo** [joxeankoret/diaphora#185]
Environment : Ida 7.4, IdaPython 7.4.0 , Python 3.8.1 ,  diaphora version = main branch , windows 7 .

I tried to load diaphora script from Ida and got this error

<path_to_diaphora.py> the sip module has already registered a module called PyQt5.PyCore
Traceback:
File c:\Program Files\Ida Pro7.4\python\ida_idaapy.py,line 590 in IDAPython_ExecScript exec(code,g)
File <path_to_diaphora.py> line 2135 in <module> exec (compile(open(script,"rb").read(),script,'exec'))
File <path_to_diaphora_ida.py> line 46 in <module>
from PyQt5 import QtCore, QtGui, QtWidgets
RuntimeError:the sip module has already registered a module called PyQt5.PyCore

**Comment by joxeankoret** [comment]
I cannot make sense of the error. Can you please try running ```idapyswitch```, setting up the proper Python version and re-running again?

Also, Python 3.8 is very broken. Please try with a 3.7 version if the previous doesn't work.

**Comment by paramikoooo** [comment]
I tried to install python 3.7.0  . Ida recognize it as well.
I can run my python script , but when I tried to run diaphora.py I got Error

> Dll load failed:The specified module could not be found.
> Traceback:
> File c:\Program Files\Ida Pro7.4\python\ida_idaapy.py,line 590 in IDAPython_ExecScript exec(code,g)
> File <path_to_diaphora.py> line 2135 in exec (compile(open(script,"rb").read(),script,'exec'))
> File <path_to_diaphora_ida.py> line 46 in
> from PyQt5 import QtCore, QtGui, QtWidgets
>ImportError: DLL load failed : The specified module could not be found.

**Comment by joxeankoret** [comment]
Did you manage to get it fixed?

**Comment by syntroniks** [comment]
I'm able to reproduce this. Using Python 3.7 solves it for me.

**Comment by joxeankoret** [comment]
OK, I will close this issue for now. If anybody reproduces it and cannot fix it by installing a supported Python version, feel free to reopen.
