### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0

### ISSUE THREAD

**Issue by PSR009** [joxeankoret/diaphora#188]
Hi, I'm new to IDAPython. So, please help me out if it's resolved already or silly.

I've got the following issue while using `graph.exe` component of MS Office.
It works with other Windows applications and DLL's but not this.
My environment is Ubuntu 18.04, with Diaphora 2.0.2 and:
```
Python 3.6.9
[GCC 8.4.0]
IDAPython 64-bit v7.4.0 final
```

While exporting it says:
```bash
Error: 'utf-8' codec can't decode byte 0xb0 in position 23: invalid start byte
Traceback (most recent call last):
  File "/home/user/Documents/diaphora-master/diaphora_ida.py", line 2284, in _diff_or_export
    bd.export()
  File "/home/user/Documents/diaphora-master/diaphora_ida.py", line 836, in export
    self.do_export(crashed_before)
  File "/home/user/Documents/diaphora-master/diaphora_ida.py", line 790, in do_export
    props = self.read_function(func)
  File "/home/user/Documents/diaphora-master/diaphora_ida.py", line 1653, in read_function
    str_constant = str_constant.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 23: invalid start byte
```
Files link:
https://drive.google.com/drive/folders/1WocDZop4u1C87f6Xmqdc0CFK3VvsY0pK?usp=sharing

Thanks!

**Comment by joxeankoret** [comment]
Thanks for the files! I will try to reproduce...

**Comment by joxeankoret** [comment]
Fixed with https://github.com/joxeankoret/diaphora/commit/5c8df26310c5f0872bb4124f429fb3891712d61b. Thanks for reporting!
