### ISSUE TITLE
Diaphora failing to parse sqlite

### ISSUE THREAD

**Issue by AxelPotato** [joxeankoret/diaphora#192]
I am receiving the following error when comparing 2 sqlites.
Most of the time I do not get this error but sometimes it just crops up.

Traceback (most recent call last):
  File "diaphora.py", line 2163, in <module>
    bd.diff(db2)
  File "diaphora.py", line 2076, in diff
    if self.equal_db():
  File "diaphora.py", line 586, in equal_db
    cur.execute(sql)
sqlite3.OperationalError: SELECTs to the left and right of EXCEPT do not have the same number of result columns.

This is the offending sql query:
`sql = "select count(*) total from (select * from functions except select * from diff.functions) x"`

It regards the following piece of code:

```
  def equal_db(self):

    cur = self.db_cursor()
    sql = "select count(*) total from program p, diff.program dp where p.md5sum = dp.md5sum"
    cur.execute(sql)
    row = cur.fetchone()
    ret = row["total"] == 1
    if not ret:
      sql = "select count(*) total from (select * from functions except select * from diff.functions) x"
      cur.execute(sql)
      row = cur.fetchone()
      ret = row["total"] == 0
    else:
      log("Same MD5 in both databases")
    cur.close()
    return ret
```

I removed the: 
`except select * from diff.functions`

And I got the following error:

Traceback (most recent call last):
  File "diaphora.py", line 2163, in <module>
    bd.diff(db2)
  File "diaphora.py", line 2090, in diff
    self.find_equal_matches_parallel()
  File "diaphora.py", line 1024, in find_equal_matches_parallel
    cur.execute(sql)
sqlite3.OperationalError: SELECTs to the left and right of INTERSECT do not have the same number of result columns
Finished comparing. Now parsing sqlites to JSON

this was the offending sql:
` "select address ea, mangled_function, nodes from (select * from functions intersect select * from diff.functions) x"`

```
   def find_equal_matches_parallel(self):
    cur = self.db_cursor()
    # Start by calculating the total number of functions in both databases
    sql = """select count(*) total from functions
             union all
             select count(*) total from diff.functions"""
    cur.execute(sql)
    rows = cur.fetchall()
    if len(rows) != 2:
      Warning("Malformed database, only %d rows!" % len(rows))
      raise Exception("Malformed database!")

    self.total_functions1 = rows[0]["total"]
    self.total_functions2 = rows[1]["total"]

    sql = "select address ea, mangled_function, nodes from (select * from functions intersect select * from diff.functions) x"
    cur.execute(sql)
    rows = cur.fetchall()
    if len(rows) > 0:
      for row in rows:
        name = row["mangled_function"]
        ea = row["ea"]
        nodes = int(row["nodes"])

        self.best_chooser.add_item(CChooser.Item(ea, name, ea, name, "100% equal", 1, nodes, nodes))
        self.matched1.add(name)
        self.matched2.add(name)
    cur.close()

    if not self.ignore_all_names:
      self.find_same_name(self.partial_chooser)

    self.run_heuristics_for_category("Best")
```

I removed the:
` intersect select * from diff.functions`
 from the query and the comparison ran just fine.

I have no idea what are the implications of removing these parts of the sql query on other file compares.

**Comment by AxelPotato** [comment]
Quick update... it did not work as expected ^^
they just get compared to the same file.

So my fix is of no help.

**Comment by AxelPotato** [comment]
I believe I found the issue.
I had an sqlite from an older version of diaphora getting compared to an sqlite I made with version 2.0
And now that im looking into it there is an extra column 'userdata' in the sqlites made by version 2.0.

**Comment by joxeankoret** [comment]
Yes, it's always that the problem when you get the error "sqlite3.OperationalError: SELECTs to the left and right of INTERSECT do not have the same number of result columns". I will add this to the list of things to review and refactor. Thanks for reporting!
