### ISSUE TITLE
Will / Does diaphora supports HotColdSplitting Optimized Binaries

### ISSUE THREAD

**Issue by Naville** [joxeankoret/diaphora#199]
[Reference](https://www.youtube.com/watch?v=Q8rqGg6vHAE)
Basically it's a compiler optimization that splits out the "cold" basicblocks (BBs that rarely got actually executed) and split them into a separate function. 

I'd assume this sort of splitting breaks Diaphora's analysis algorithms

**Comment by joxeankoret** [comment]
Uhm... Diaphora does nothing right now with cold basic blocks. I will research about them. Thanks for pointing it out!

**Comment by Naville** [comment]
Ping. One idea at the top of my head is to allow generic inlining of whatever intermediate representation diaphora is currently using. From there the user should be able to config whether a function is to be inlined thus achieving whatever is required here

**Comment by joxeankoret** [comment]
I know this is an old issue but, does anyone have such binaries? I cannot find anywhere how to build them myself.

**Comment by joxeankoret** [comment]
I'm closing it for now as there is nothing I can see I should be doing here. Feel free to reopen if you have binaries to test.

**Comment by Naville** [comment]
This seems to be heavily used on Darwin/*OS Kernel / SystemLibraries.

That being said, IDA themselves tried to implement one but didnt work well :(
