### ISSUE TITLE
diaphora doesn't support radare2

### ISSUE THREAD

**Issue by crowell** [joxeankoret/diaphora#2]
it would be awesome if diaphora could be used as a plugin for [radare2](http://github.com/radare/radare2) as well as for ida.

**Comment by joxeankoret** [comment]
Support for Radare2 is planned but it lacks many things we need:

 * A stable Python API. Talking with pancake, we will likely use the r2pipe interface.
 * Function prototypes as well as mangled & demangled function names.
 * An interface to get the comments for functions, basic blocks and per-instruction.

These problems are minor but writing the Radare2 exporter is not a critical issue at this point. Do you want to write/collaborate writing it yourself?

**Comment by dwendt** [comment]
dropping a :+1: 

but I'd definitely make sure the r2pipe interface isn't going to change drastically before doing this

**Comment by assarbad** [comment]
:+1:

**Comment by trufae** [comment]
Forked here https://github.com/radare/diaphora

we basically need to remove ALL the ida and gui related code from the diaphora_r2.py script, help is welcome to remove all that trash

**Comment by joxeankoret** [comment]
If you need help, tell me! Basically, I think that you need to rewrite the function read_function().

**Comment by trufae** [comment]
Did u merged?

**Comment by joxeankoret** [comment]
Working on it

**Comment by enovella** [comment]
Reopen please...
