### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by vandir** [joxeankoret/diaphora#201]
It could be useful to add a command line interface to bulk the analysis when you have many (maybe) similar executables.

What do you think?

**Comment by joxeankoret** [comment]
It's possible to automate, but I'm afraid you will need to script it a bit. This is an example of how you can automate the export and diffing process for each file:
https://github.com/joxeankoret/diaphora/wiki/How-can-I-automate-the-diffing-process%3F

**Comment by vandir** [comment]
Many thanks! You may want to add that in the following command:

`$ ida -A -B -S/path/to/diaphora.py your_binary`

"/path/to/diaphora.py" should not contain any space (it's maybe an IDA bug)

**Comment by joxeankoret** [comment]
You're right!
