### ISSUE TITLE
Import diaphora to Ida Python script

### ISSUE THREAD

**Issue by joroMaser** [joxeankoret/diaphora#204]
How can I import diaphora project to my Ida Python script to find diff between 2 functions in 2 binaries, without using diaphora GUI?

**Comment by joxeankoret** [comment]
Doing the diffing part is not hard and can be done even in the command line (after exporting each database). Take a look to this to know how to automate that part:

https://github.com/joxeankoret/diaphora/wiki/How-can-I-automate-the-diffing-process%3F

However, to visualize the matches you will need to write your own tools to consume the SQLite database that is generated.

**Comment by joroMaser** [comment]
1)I have Ida in Windows not in Linux.

Can I export that vars in Windows?

2)there is no exported functionality to analyze output.db? (the diff db) just to look at specific function to look the difference

**Comment by joxeankoret** [comment]
Hi @joroMaser, sorry for taking that long. 

So, for #1: Yes, absolutely, you can. As for #2, there is no functionality exported whatsoever because the diff is exported to a SQLite database that can be opened with any tool that can read SQLite databases.

**Comment by joxeankoret** [comment]
I'm closing this issue as I think I have helped you. If you need more help or whatever, feel free to reopen it.
