### ISSUE TITLE
Apply C++ demangling to "Name" field?

### ISSUE THREAD

**Issue by CaledoniaProject** [joxeankoret/diaphora#205]
I have created a simple C++ program to test diaphora, 

![screenshot 2021-01-09 at 10 40 53 AM](https://user-images.githubusercontent.com/1357701/104081072-4f458f80-5267-11eb-9045-167a63565ea1.jpg)

The method name `run(int)` is correctly demangled by IDA, but diaphora still uses `__Z3runi`.

Can you add an option to demangle C++ names?

**Comment by CaledoniaProject** [comment]
Attached main.cpp

[main.txt](https://github.com/joxeankoret/diaphora/files/5790057/main.txt)

**Comment by joxeankoret** [comment]
It uses both the mangled and the demangled name, but it shows the mangled one. I'm not 100% sure we prefer to see the demangled name as, sometimes, it's very confusing with large C++ names. Let me do some tests to check if it makes things better or worst with long names...

**Comment by CaledoniaProject** [comment]
You can add an option and let the user decide ...

**Comment by joxeankoret** [comment]
As I thought, it wasn't that simple. Could you please run the following 2 Python commands in your IDA Python prompt for this database?

```py
get_func_name(here())
idc.demangle_name(get_func_name(here()), INF_SHORT_DN)
```

**Comment by CaledoniaProject** [comment]
In IDA 7.5 SP3 + Python 3.8.2

```
Python>
Python>get_func_name(here())
'_main'
Python>idc.demangle_name(get_func_name(here()), INF_SHORT_DN)
Python>
```

**Comment by joxeankoret** [comment]
Sorry, I wanted the output for some mangled function, like `run` or `run2`.

**Comment by joxeankoret** [comment]
And done, fixed with this commit: https://github.com/joxeankoret/diaphora/commit/241eabba1917847b7b409bff5ec70f1e370d31f6
The problem was that the heuristic "Perfect match, same name" was taking the mangled name instead of the demangled name, in opposite to all the other heuristics. Thanks for reporting!
