### ISSUE TITLE
UnboundLocalError: local variable 'succ_block' referenced before assignment

### ISSUE THREAD

**Issue by fatrolls** [joxeankoret/diaphora#207]
Normally I have no problem using diaphora.. but 1 case, doesn't seem to export sqlite database

I get this error

![error](https://i.imgur.com/rQLKEQX.png)

yes bug is real

I don't know python at all but I fixed the bug from a stackoverflow question.
Here is my fix

I added

```
global succ_block
```

under

```
    constants = []
```

on line 1570

![fix](https://i.imgur.com/x4H9qXA.png)

Works good now! :)

I noticed you recently fixed this bug in the last commit I downloade the old version `"Diaphora 2.0.2 Latest on Oct 18, 2019"`

So yeah.. now it seems to work fine after I re-downloaded the last whole github project.

No problems anymore. You sure it has to be pred_block instead of succ_block ?

**Comment by joxeankoret** [comment]
Hi! This bug was fixed with this commit some time ago: https://github.com/joxeankoret/diaphora/commit/b019145d1efdcadbdafd6ea95f3d579bc698fbda
