### ISSUE TITLE
IDA 7.6? Is that true?

### ISSUE THREAD

**Issue by yasong** [joxeankoret/diaphora#216]
![image](https://user-images.githubusercontent.com/9759407/109442394-09d95d80-7a73-11eb-8d1f-0a9e6d8156d2.png)

**Comment by joxeankoret** [comment]
Yes, it is working with the latest beta version of IDA 7.6. I routinely test, and adapt if required, every new IDA version before it's released.

**Comment by yasong** [comment]
> Yes, it is working with the latest beta version of IDA 7.6. I routinely test, and adapt if required, every new IDA version before it's released.

OK! Thank you. Please forgive me. I didn't find the IDA 7.6 on hex-ray website.

**Comment by yEsPaP** [comment]
> Yes, it is working with the latest beta version of IDA 7.6. I routinely test, and adapt if required, every new IDA version before it's released.

but latest i can find is  IDA and decompilers v7.5.201028 ???

**Comment by joxeankoret** [comment]
IDA 7.6 is still in beta.
