### ISSUE TITLE
Empty list filter bug

### ISSUE THREAD

**Issue by BlueAmulet** [joxeankoret/diaphora#219]
I looked in the resulting sqlite db and noticed that all empty lists for things like names and switches columns show up as `[]`
![2021-05-08_111542](https://user-images.githubusercontent.com/43395286/117547798-d37a0a80-afee-11eb-95b6-40d60d0a16e9.png)

But the SQL in diaphora_heuristics.py checks for empty lists by doing `and f.names != '{}'`

**Comment by joxeankoret** [comment]
You're right. I thought I had fixed it but, I didn't. I will fix it for good. Thanks for reporting!
