### ISSUE TITLE
Use time.monotonic() instead of time.time()

### ISSUE THREAD

**Issue by BlueAmulet** [joxeankoret/diaphora#220]
Whenever the system time changes, as a result of DST or VM resuming, the result of time.time() can wildly change throwing off any ETA estimate, elapsed time measure, or timeouts.

time.monotonic() has the same resolution and tick rate as time.time() does, except that it's not affected by system time changes, and has been around since python 3.3 for compatibility concern.

**Comment by joxeankoret** [comment]
Done!

**Comment by fr0gger** [comment]
Hey, I get an error with monotonic on IDA 7.2, it is fixed by using time.time() instead. :)

**Comment by BlueAmulet** [comment]
IDA before 7.4 uses Python 2
See https://github.com/joxeankoret/diaphora/issues/197
