### ISSUE TITLE
IDA Pro 7.5 Crashes when loading diaphora.py

### ISSUE THREAD

**Issue by bahnz** [joxeankoret/diaphora#221]
IDA Pro 7.5 crashes upon loading diaphora.py. 

![image](https://user-images.githubusercontent.com/9594159/121891730-72c2a980-cce1-11eb-98ea-c4eb0f03a470.png)

**Comment by joxeankoret** [comment]
Uhm... That sounds super weird. I think I'm going to need more context because there are many users of IDA 7.5 using Diaphora and nobody reported this crash.

**Comment by joxeankoret** [comment]
Some things to verify:

* Does it happen with vanilla IDA (ie: without extra plugins)?
* Do you have Python 3 x64 installed?
* Can you run any Python command in the Python prompt from within IDA?

If every answer to this is "yes", then... I am a bit at loss.

**Comment by bahnz** [comment]
- Does it happen with vanilla IDA (ie: without extra plugins)? - Yes
   - Do you have Python 3 x64 installed? - Yes 3.9.4 (64-bit)
   - Can you run any Python command in the Python prompt from within IDA?
   -Yes, other scripts work just fine.

**Comment by joxeankoret** [comment]
Aaah, now I know! You're using Python 3.9 with an IDA version that is lower than IDA 7.5 SP3:
https://hex-rays.com/blog/python-3-9-support-for-ida-7-5/

As a workaround (in case you cannot upgrade IDA for a reason), downgrade Python to 3.8 or something like that.

**Comment by bahnz** [comment]
Updated and that fixed it! Thank you!

**Comment by joxeankoret** [comment]
You are welcome!
