### ISSUE TITLE
sqlite3.OperationalError: database or disk is full

### ISSUE THREAD

**Issue by Chrys4lisfag** [joxeankoret/diaphora#224]
I am getting this error when comparing two sql databases tho i have lot of free space. I guess there is kind of a limit (I compare kinda big bins)

Is there a way to change this limit somewhere?

**Comment by joxeankoret** [comment]
When do you get that error: at exporting or diffing time?

**Comment by Chrys4lisfag** [comment]
When diffing two exported sql. Sadly, I forgot to check at what diffing method it appears (closer to last one I think)

**Comment by Chrys4lisfag** [comment]
If you need something to check, tell me and I will start analysis again. Also, when this error occurs, it gets stuck at running "python script" and you can't even cancel it. The only way to terminate IDA in task manager. I tried to wait 48h but it just got stuck after that error

**Comment by Chrys4lisfag** [comment]
The size of both sql's are ~3.9gb and ~3.9gb as well

**Comment by joxeankoret** [comment]
Uhm... I believe I know the reason. Give me some time to verify on my end (withouth having you to send me some ~8 GB of databases or corresponding).

**Comment by joxeankoret** [comment]
OK, I think I know: your temporary directory volume/drive might be too small for the big queries it needs to issue. Try changing the $TMP, $TMPDIR or whatever applies in your operating system. Otherwise, I believe I will need to play with some SQLite pragmas (like "pragma temp_store = 2;").

**Comment by Chrys4lisfag** [comment]
It is strange but it worked this time. It still was trying to create temp files in %appdata% folder tho I moved TMP and TEMP path in Windows to D drive.

I as well deleted some files from C drive to empty some space so I had ~150gb free this time. Idk what happened could it really make 100gb of cache last time?

Not fully sure what helped me. Was it emptying the drive or moving tmp folder or other magic but now it works. Thanks!

**Comment by joxeankoret** [comment]
You are welcome! BTW: remember to save to the diffing results so you don't need to redo the diffing again :)
