### ISSUE TITLE
Reload existing databases?

### ISSUE THREAD

**Issue by frankmarco2000** [joxeankoret/diaphora#225]
Hello,
How can you just reload the saved (sqlite) databases if you close out IDA and reopen?

I don't see a way to do that. Or I may just be missing something. 
If I load the script diaphora.py it ask for a place to export the current IDA project and an existing one to compare against. 

Also will diaphora need to re-analyze or will it load the previous analysis?

Thank you

**Comment by frankmarco2000** [comment]
Please ignore.

I now see how to do what I was asking.

Sorry.

**Comment by joxeankoret** [comment]
For anyone else having the same doubt: use the script diaphora_load.py.
