### ISSUE TITLE
Missing Graph Information?

### ISSUE THREAD

**Issue by frankmarco2000** [joxeankoret/diaphora#226]
Hello,
I am getting the message "Sorry, graph information is not available for one of the databases"

Can you please explain why this would be occurring?
And what I can do to fix this issue.

Thank you,

**Comment by joxeankoret** [comment]
It happens because you exported one of the databases with the option "Do not export instructions and basic blocks". If that's not the case and you still get this after exporting the 2 database being sure that option is not checked, please tell as this is a bug.
