### ISSUE TITLE
diaphora crashes IDA 7.6  with python 3.9 (master repo)

### ISSUE THREAD

**Issue by wookong007** [joxeankoret/diaphora#231]
C:\Users\WooKong007\Desktop\diaphora-master\diaphora-master\diaphora.py: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 7.6\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/WooKong007/Desktop/diaphora-master/diaphora-master/diaphora.py", line 2168, in <module>
    exec(compile(open(script, "rb").read(), script, 'exec'))
  File "C:/Users/WooKong007/Desktop/diaphora-master/diaphora-master\diaphora_ida.py", line 48, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.

**Comment by joxeankoret** [comment]
It looks like a problem with QT, not exactly with Diaphora. If you want to test it, try running the following line in the Python prompt in IDA:

``` from PyQt5 import QtCore, QtGui, QtWidgets```

If it fails, try running `idapyswitch` on the command line to see if you can fix this problem.

**Comment by matteyeux** [comment]
Hey, 

I had the same issue on my Windows box, running `idapyswitch` fixed it, thanks.

**Comment by joxeankoret** [comment]
Closing it. Feel free to reopen if you are having problems.
