### ISSUE TITLE
Timeout?

### ISSUE THREAD

**Issue by sunbeam906** [joxeankoret/diaphora#232]
I'm diffing 2 versions of the same game, one with a pdb, the other the most recent one. The first .sqlite is 2GB, the latter one is 5GB. IDA 7,7 is being used and I end-up with a (seemingly) halt here:

![image](https://user-images.githubusercontent.com/148178/169515467-e570db20-04a0-484c-843f-97d6587a6636.png)

The last "Timeout" message is from **2 hours ago**.

At some point even the "Running Python script" window vanishes and can't find any result windows (F3). Each game has over 250K functions.

Any setting I can further adjust in diaphora to push it forward in case it stopped in that "Timeout" portion? I can't even tell from the GUI if it's doing something or just frozen. Task manager shows this:

![image](https://user-images.githubusercontent.com/148178/169515772-6ed79ced-ff4f-4fe7-aa7f-37b39a20d951.png)

Any feedback is appreciated.

Best regards,
Sun

**Comment by joxeankoret** [comment]
Uhm... it sounds a bit odd. Try diffing them from outside IDA, as shown here:

https://github.com/joxeankoret/diaphora/wiki/How-can-I-automate-the-diffing-process%3F

Diaphora can diff on the command line and then, later on, you can load the results in IDA using the script `diaphora_load.py`.

**Comment by sunbeam906** [comment]
Several hours later, same status :)

![image](https://user-images.githubusercontent.com/148178/169583060-d2a24c02-1285-4ec2-a075-24b28a459608.png)

Will try what you proposed.

**Comment by joxeankoret** [comment]
Any luck?

**Comment by sunbeam906** [comment]
> Any luck?

Sorry for replying this late. I think I abandoned my attempt, since I was diffing a Nintendo Switch sqlite against a PC one, both massive. With small dbs it works perfectly fine. Takes a bit, but fine.

I've closed this. Thanks!
