### ISSUE TITLE
Numeric columns aren't sorted numerically

### ISSUE THREAD

**Issue by wdormann** [joxeankoret/diaphora#233]
When you diff two binaries, one of the columns is called "BBlocks1", which has integer values.
If you sort this column, you'll end up with orders like:

12
125
13
14
140
15

Ideally, columns of this type would be sorted numerically instead.

**Comment by joxeankoret** [comment]
That's the problem with choosers and IDA Python: we don't have that option. Sorting is by text always. What I can do is like what I did with the number column: append zeros.

**Comment by joxeankoret** [comment]
I'm closing it for now as there is no way, or I don't know any, to fix this with IDA for now.
