### ISSUE TITLE
undefined function __plugins IDA 7.7

### ISSUE THREAD

**Issue by steve007iii** [joxeankoret/diaphora#234]
something changed for ida pro 7.7 
I don't know what it could be

`C:\Isolation\IDA Pro 7.7\plugins\diaphora.py: undefined function __plugins__diaphora.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_heuristics.py: undefined function __plugins__diaphora_heuristics.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_ida.py: undefined function __plugins__diaphora_ida.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_import.py: undefined function __plugins__diaphora_import.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_load.py: undefined function __plugins__diaphora_load.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_load_and_import.py: undefined function __plugins__diaphora_load_and_import.PLUGIN_ENTRY`

x2
`C:\Isolation\IDA Pro 7.7\plugins\diaphora.py: undefined function __plugins__diaphora.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_heuristics.py: undefined function __plugins__diaphora_heuristics.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_ida.py: undefined function __plugins__diaphora_ida.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_import.py: undefined function __plugins__diaphora_import.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_load.py: undefined function __plugins__diaphora_load.PLUGIN_ENTRY
C:\Isolation\IDA Pro 7.7\plugins\diaphora_load_and_import.py: undefined function __plugins__diaphora_load_and_import.PLUGIN_ENTRY`

I have no problem with imports.

**Comment by joxeankoret** [comment]
Uhm... you don't need to copy Diaphora to the plugins folder. Indeed, it's not a proper IDA plugin, so these warnings are normal. Move it to some another folder and use "Run script" from within IDA to run the plugin.

**Comment by joxeankoret** [comment]
Closing it for now, feel free to reopen if you have any problem.
