### ISSUE TITLE
Duplicates in bb_relations

### ISSUE THREAD

**Issue by Myles1** [joxeankoret/diaphora#239]
Thank you so much for writing this software! It's really very useful.

Just a heads up that I'm seeing lots of duplicates in the `bb_relations` table. Maybe user error on my end, maybe something else? Feel free to reach out if it's not occurring on your end and you'd like a repro.

**Comment by joxeankoret** [comment]
Uhm... It looks odd, I will try to repro and otherwise ping you again to get a sample

**Comment by joxeankoret** [comment]
Could you share a sample, please?

**Comment by joxeankoret** [comment]
I cannot reproduce in 2.0 or in the beta version of 3.0. Feel free to reopen if you see this happening again.
