### ISSUE TITLE
Display call graph differences

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#24]
Not easy: how can I display in a useful way the differences from huge call graphs in an IDA's GraphViewer? Collapsing some nodes between this and that path?

**Comment by shuffle2** [comment]
Maybe you could do something like GraphSlick ida plugin, which collapses the common sub-graph to a single node?

**Comment by joxeankoret** [comment]
I'm afraid that doing so from Python is problematic at best and, more likely, not possible. But I can simulate the collapsing of nodes. Is an option.

**Comment by joxeankoret** [comment]
NOTE: At least as a debugging option, showing a call-graph of the matched functions, can be useful.

**Comment by joxeankoret** [comment]
Does anybody consider this any useful?
