### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by HongThatCong** [joxeankoret/diaphora#245]
Hi @joxeankoret 
I found some bugs in source files: diaphora.py and diaphora_ida.py
1. diaphora.py
Form https://github.com/joxeankoret/diaphora/blob/a369c7caf119a7d6ad8414772b1f18f1b244c795/diaphora.py#L1335 to https://github.com/joxeankoret/diaphora/blob/a369c7caf119a7d6ad8414772b1f18f1b244c795/diaphora.py#L1349
unreliable and partial variable still None, cause Exception.
Need check None.

2. diaphora_ida.py
2.1. import_instruction_level function:
Line: https://github.com/joxeankoret/diaphora/blob/a369c7caf119a7d6ad8414772b1f18f1b244c795/diaphora_ida.py#L1365
Should be same as line https://github.com/joxeankoret/diaphora/blob/a369c7caf119a7d6ad8414772b1f18f1b244c795/diaphora_ida.py#L1387
Missing: "ins.operand_names operand_names" in sql statement

2.2. Line https://github.com/joxeankoret/diaphora/blob/a369c7caf119a7d6ad8414772b1f18f1b244c795/diaphora_ida.py#L1384
Should be same as line https://github.com/joxeankoret/diaphora/blob/a369c7caf119a7d6ad8414772b1f18f1b244c795/diaphora_ida.py#L1401

2.3. Need check  operand_names is empty

Thanks you very much, @joxeankoret

**Comment by joxeankoret** [comment]
Hi! Unfortunately, it seems it's showing wrong lines right now for `diaphora.py`. Would you mind please updating it?

**Comment by joxeankoret** [comment]
I have (locally) fixed the problem with importing at instruction level. Thank you very much for reporting this! I will have to modify my testing suite to also test importing symbols.

**Comment by gottfriedleibniz** [comment]
The other issue being reported are cases where the `partial` and `unreliable` choosers may be `None`.

For example, follow: [self.add_matches_from_cursor_ratio_max](https://github.com/joxeankoret/diaphora/blob/2f2c847c05292b192bedb06ce0019e290eb14d5b/diaphora.py#L1816) to [partial.add_item](https://github.com/joxeankoret/diaphora/blob/2f2c847c05292b192bedb06ce0019e290eb14d5b/diaphora.py#L1330), [partial.add_item](https://github.com/joxeankoret/diaphora/blob/2f2c847c05292b192bedb06ce0019e290eb14d5b/diaphora.py#L1345), and [unreliable.add_item](https://github.com/joxeankoret/diaphora/blob/2f2c847c05292b192bedb06ce0019e290eb14d5b/diaphora.py#L1350)

**Comment by joxeankoret** [comment]
Aaah, I see. Already fixed locally, I will commit later (whenever I have time).

**Comment by 0x79H** [comment]
> Everything should be fixed with [ebb3350](https://github.com/joxeankoret/diaphora/commit/ebb3350ee9607705f46c9365fc74e20d93591f7a) and [466c706](https://github.com/joxeankoret/diaphora/commit/466c706e66cae53b85749b477a2cb0e3ea37f62e)

`AttributeError: 'NoneType' object has no attribute 'add_item'`
partial is None at
https://github.com/joxeankoret/diaphora/blob/466c706e66cae53b85749b477a2cb0e3ea37f62e/diaphora.py#L1330
because `partial = None`
https://github.com/joxeankoret/diaphora/blob/466c706e66cae53b85749b477a2cb0e3ea37f62e/diaphora.py#L1816
same at
https://github.com/joxeankoret/diaphora/blob/466c706e66cae53b85749b477a2cb0e3ea37f62e/diaphora.py#L1878
I didn't read the code but I fix like ebb3350, it just work, but I don't know if it would break the code.

**Comment by joxeankoret** [comment]
Ah, you're right. The thing is that these problems are fixed in my development branch, which greatly differs from the current public one, I have to manually port all the changes and... I missed various. Thanks for reporting! I will fix it 'soon'.

**Comment by joxeankoret** [comment]
And done. Thank you very much for reporting!
