### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by JonhSilver** [joxeankoret/diaphora#248]
How to install and how to compare two exe files?

C:\Users\diaphora-master\diaphora_ida.py:21: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "C:\Users\diaphora-master\diaphora_ida.py", line 31, in <module>
    from idc import *
ModuleNotFoundError: No module named 'idc'

**Comment by JonhSilver** [comment]
pip install idc
Collecting idc
  Using cached idc-0.6.0.tar.gz (850 kB)
  Preparing metadata (setup.py) ... done
Collecting pyOSC==0.3.5b-5294
  Using cached pyOSC-0.3.5b-5294.tar.gz (33 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\AppData\Local\Temp\pip-install-fo6a0xaj\pyosc_e315fdef81a1469cabf40ce9b054f211\setup.py", line 5, in <module>
          import OSC
        File "C:\Users\AppData\Local\Temp\pip-install-fo6a0xaj\pyosc_e315fdef81a1469cabf40ce9b054f211\OSC.py", line 735
          binary = struct.pack('>ll', 0L, 1L)
                                       ^
      SyntaxError: invalid syntax
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by joxeankoret** [comment]
Hi! I'm afraid you are confusing how it works. You will need IDA to export both binaries before being able to find the differences. For diffing, after you have two binaries analyzed with IDA and exported to SQLite databases with Diaphora, you can use diaphora.py for diffing them, but you will need first to run diaphora_ida.py from within IDA.

**Comment by joxeankoret** [comment]
I'm closing it for now. If you encounter problems using it from within IDA feel free to reopen.
