### ISSUE TITLE
Windows - Python 3.11 - No module named _sqlite3

### ISSUE THREAD

**Issue by matbech** [joxeankoret/diaphora#249]
On Windows, with Python 3.11.1 I get the following error when loading the script:
No module named '_sqlite3'

With Python 3.10.x it is working as expected.

It looks like the sqlite module is (accidentally) missing in the Windows Python 3.11 installer.

**Comment by joxeankoret** [comment]
That would be a bug on the Python side. I think it should be reported to their maintainers. I'm, by the way, very surprised that happened.

**Comment by joxeankoret** [comment]
I'm sorry, I will close it for now as it seems to be a very Python 3.11 for Windows bug:

https://stackoverflow.com/questions/75097075/python-3-11-installation-some-modules-are-missing

Feel free to reopen if you have related problems or you believe I'm mistaken in this case.
