### ISSUE TITLE
In dark mode the colors are not clear

### ISSUE THREAD

**Issue by yooo1999** [joxeankoret/diaphora#254]
In IDA dark mode , in diff screen the colors are not clear

**Comment by joxeankoret** [comment]
Some ~4 persons complained about this. But the problem is that everyone is using, in general, a different IDA dark mode plugin or scheme. Please can you tell me which plugin are you using?

**Comment by Mas0nShi** [comment]
> Some ~4 persons complained about this. But the problem is that everyone is using, in general, a different IDA dark mode plugin or scheme. Please can you tell me which plugin are you using?

The default theme dark is almost unreadable...

<img width="848" alt="image" src="https://user-images.githubusercontent.com/60805843/229255169-428210ea-e94e-4c90-af6b-c7a324850f07.png">

**Comment by yooo1999** [comment]
@joxeankoret The default dark mode like @Mas0nShi  show

**Comment by joxeankoret** [comment]
Uhm... To be honest, I don't know how to properly automate it. But I can do a very easy thing: a configuration file where, also, colours can be configured. So, in the case of people with uncommon colour schemes, like in these cases, you could choose your preferred colours. I would need to write a backport for Diaphora 2.X first and then integrate it into 3.0, but that's my problem, not yours :)

So, does it sound about right to you folks?

**Comment by Bukl198** [comment]
hi there, sorry for opening a closed issue, will it be possible for you to send me the beta link for 3.0 as well? i would like to modify the colors as highlighted here as well, thank you
