### ISSUE TITLE
there are many handles to *.sqlite db still opened

### ISSUE THREAD

**Issue by marakew** [joxeankoret/diaphora#255]
after using plugin and change idb to another
sqlite db still has open handles

env windows but i thinks same issue will under linux and macosx

**Comment by joxeankoret** [comment]
Yes, this is a known issue with the current published version that is fixed in the still in development 3.0. It isn't published yet and it won't be published until June 2023, but I can send you the current beta version if you want to test.

**Comment by marakew** [comment]
iam no rush
just playing with different bindiff software

**Comment by HongThatCong** [comment]
Yes, it still a bug in current version of Diaphora.
I have tried to close, del sqlite db object but not sucessed. It still locked.
Can I participate in testing the new diaphora version?
Tks @joxeankoret

**Comment by joxeankoret** [comment]
Yes, of course, you can beta test it. Please give me your email or some way to privately send you it.
