### ISSUE TITLE
Create an external GUI tool

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#26]
The tool must be able to:
- Browse/examine exported SQLite databases. Think of a read-only IDA version.
- Load saved diffing results. Depends on bug  #11.
- Allow taking notes and comments over the results.

The tool should be supported in any device so it will be a web application.

**Comment by nanotechz9l** [comment]
Something similar to the standalone bindiff.jar file gui would be neat. Support for multiple work spaces via different tabs, etc.

**Comment by joxeankoret** [comment]
If somebody has some idea on this subject that doesn't mean Java or QT+C++, I would be thankful. My only idea so far: write a (local only) web application and use JavaScript based frameworks for showing the graphs. I dislike this idea, BTW.
