### ISSUE TITLE
"Interesting matches" subview isn't re-opened when F3 is pressed

### ISSUE THREAD

**Issue by wdormann** [joxeankoret/diaphora#266]
I'm using the current github version of Diaphora.
When running Diaphora for the first time, a view called "Interesting matches" is opened, which appears to be a subset of "Partial matches".
If I close up the Diaphora tabs (e.g. because they weren't placed in the right area in IDA), and then hit F3 to open the Diaphora subviews again, the "Interesting matches" subview is **not** opened again.  It's unclear how this subview can be viewed again.

**Comment by joxeankoret** [comment]
Aaaah, you are right, I missed it. Thanks for reporting!

**Comment by joxeankoret** [comment]
Should be fixed with 706308b. Feel free to reopen if it does not.
