### ISSUE TITLE
The Diaphora window cannot be resized

### ISSUE THREAD

**Issue by r0ny123** [joxeankoret/diaphora#267]
After running the `diaphora.py` within IDA, the Diaphora window opens (see screenshot), which can not be resized anymore. Hence, there's a problem viewing the `OK` and `Cancel` buttons at the bottom.
 
![image](https://github.com/joxeankoret/diaphora/assets/49360849/5c748315-77d0-4715-9e7a-9810eed3fb73)

**Comment by joxeankoret** [comment]
Aaah, now I see the problem. I'm reverting back my change to move the "Export filter limits" option (will commit soon, after work). There is little I can do with the current (IDA's) system to generate GUIs. The proper fix for this would be to create this UI dialogue with PyQT instead.

**Comment by joxeankoret** [comment]
Should be fixed with 706308b. Feel free to reopen if it does not.
