### ISSUE TITLE
The ability to only diff certain functions

### ISSUE THREAD

**Issue by mspublic** [joxeankoret/diaphora#28]
This is far from critical but one nice thing in BinDiff is the ability to only export/diff certain functions. If someone already has an idea where the target spot has changed this is a very helpful feature when dealing with very large idbs.

**Comment by joxeankoret** [comment]
There is a way to limit what to export or diff. You can export or diff only whatever is on the address limits, use the options at the right side of the SQLite's databases path.

**Comment by mspublic** [comment]
My mistake - was looking at the function diff in bindiff and completely forgot diaphora had the address export. Thanks Joxean! Closing
