### ISSUE TITLE
Diaphora does not complete diffing

### ISSUE THREAD

**Issue by mambrui** [joxeankoret/diaphora#296]
I am trying to run a diffing task from the command line using the command (from the Wiki): 

`$ python /path/to/diaphora/diaphora.py first.db second.db -o output.db`

The task completes several of the matching heuristics, however when it starts with `Same constants related matches` it constantly gets timeouts and starts processing the rows over.

![Screenshot 2024-03-04 101937](https://github.com/joxeankoret/diaphora/assets/4028749/0cd97b96-897b-428e-88e2-c5a13c155d38)

This timeout happened 13 times in a period of 2 hours.

**Comment by joxeankoret** [comment]
That sounds like a bug. Let me try to reproduce it...

**Comment by joxeankoret** [comment]
Issue fixed with the latest Diaphora version, 3.2.0.
