### ISSUE TITLE
Script crash on export execution

### ISSUE THREAD

**Issue by BigJim** [joxeankoret/diaphora#31]
Get error:
---------------------------
Warning
---------------------------
C:\Tools\IDA\python\diaphora-master\diaphora.py: local variable 'bd' referenced before assignment
Traceback (most recent call last):
  File "C:\Tools\IDA\python\idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Tools/IDA/python/diaphora-master/diaphora.py", line 3118, in <module>
    diff_or_export_ui()
  File "C:/Tools/IDA/python/diaphora-master/diaphora.py", line 3093, in diff_or_export_ui
    return _diff_or_export(True)
  File "C:/Tools/IDA/python/diaphora-master/diaphora.py", line 3090, in _diff_or_export
    return bd
UnboundLocalError: local variable 'bd' referenced before assignment

---------------------------
OK   
---------------------------

Steps:
1) Clean install of Windows IDA 6.8, except some plug-ins removed.
2) Installed "diaphora-master" folder in IDA Pro root folder.
3) Loaded a large Windows IDB (84,268 functions).
4) Executed "diaphora.py"
5) Using all default options.
6) Clicked ok.
7) Appeared to run and then error dialog appeared with above.

Update/fix:
Okay after some playing around I found that the default address range was very wrong.
It chose "HEADER:00400000" as the start address (should have been straight 00401000) and
end address was some strange address outside of any code segments "0:0013C000" something.

I manually set the start address to "00401000" and end address to "016C1E00" (the real end of the sections) and it's running now.
I'll know in an hour or so if it runs okay.

Suggestion:
Might need to pattern here like if "inf.procName == 'metapc'" and enumerate for all ".text" or class "CODE" sections. Use those for the start and end address defaults..

Good to see another Bin-Diff type plug-in/script..

**Comment by joxeankoret** [comment]
This is curious, is it a memory dump by any chance? Diaphora uses MinEA() and MaxEA() to determine the minimum and maximum addresses in the IDA database.

Also, there should be another error before the "UnboundLocalError: local variable 'bd' referenced before assignment". Do you have see any other error in the output window?

**Comment by BigJim** [comment]
Hey again.Not a memory dump, just a large (around 240mb IDB) Windows executable that's not packed or encrypted.
I posted the issue last late last night, I'll troubleshoot it when I get home today.Do you use or know of an setup to debug IDA Python scripts (where you can step through code, look at variables, etc)?

**Comment by joxeankoret** [comment]
There is nothing for debugging IDAPython scripts. I have been thinking about doing it myself but... well, not enough time :(

I'll try to do some modifications so it gives, at least, better error messages.

**Comment by pmarkowsky** [comment]
You can debug IDAPython scripts pretty easily with WingIDE's  debugger.

https://wingware.com/doc/howtos/idapython

It's not free but works well.

-Pete

**Comment by BigJim** [comment]
>https://wingware.com/doc/howtos/idapython
>It's not free but works well.
Non-Commercial Use $89 seems a little pricey to do just debugging, but then if you do a lot of IDA Python coding it does have an IDE,etc.
Maybe someone will make it their project to expose the needed Python debug APIs in their own DLL for one of the Open Source IDEs from here et al: https://wiki.python.org/moin/IntegratedDevelopmentEnvironments

**Comment by BigJim** [comment]
Okay it seems to be something to do with formatting in the main UI.
Seems you mainly work the Linux IDA, could be something different in the windows version.
Appears that "Form.FT_ADDR" gets translated either too or from a string.

Changing the two lines, replacing FT_ADDR with FT_HEX fixed the problem:
```python
'iMinEA': Form.NumericInput(tp=Form.FT_HEX, swidth=22), # FT_ADDR
'iMaxEA': Form.NumericInput(tp=Form.FT_HEX, swidth=22), # FT_ADDR
```

**Comment by joxeankoret** [comment]
Yes, I typically work more with the Linux version than with the Windows version. Patch applied with 4b82ceafc7eeae831796fb8c63230605f3d1e5bd, thanks!

**Comment by joxeankoret** [comment]
I guess the bug is fixed. Please, re-open if with the latest fixes it isn't.
