### ISSUE TITLE
Match results show 100% equal for functions with differences

### ISSUE THREAD

**Issue by grimdoomer** [joxeankoret/diaphora#313]
I'm trying to use diaphora to diff different versions of the same binary and detect functions that have differences with a granularity of single instruction changes. I noticed when diff'ing two versions of this binary that only contain a single instruction difference the match of the function is detected as "100% equal" with a ratio of 1.0 even though the functions contain a single instruction difference.
![image](https://github.com/user-attachments/assets/fd747cee-aff8-459d-9915-d9550ffcdbb2)

If I diff the assembly for the functions I can see the single instruction change:
![image](https://github.com/user-attachments/assets/03c93dc3-e3c0-4c44-925f-1885519586e5)

I understand the "lwz" line is a false positive because I changed the immediate display type in one of the databases before exporting, but I would still expect the slwi/sldi instruction change to get detected. Is there some settings I can change for the comparisons to be more strict? I thought some of the heuristics used the MD5 hash of the function data which I would expect to change between these two functions.

For additional confirmation I diff'd the two binaries in a hex editor and can clearly see the 4 byte change for the different instructions:
![image](https://github.com/user-attachments/assets/9ac4f3d3-cfe0-4bf0-9bcf-d08a597856c2)
![image](https://github.com/user-attachments/assets/732fdf79-a27c-422a-8519-3f88e9d3bb0c)

**Comment by grimdoomer** [comment]
Digging into this a bit more I got the "best" matches to run by changing `DIFFING_ENABLE_EXPERIMENTAL` to False but the results still showed "100% equal" for the function in question. I checked in the sqlite dbs to make sure the function in question has a different byte_hash between the two different versions and they are different.

In the diaphora.py file I found the `find_equal_matches` function that reports functions as "100% equal". However, it only compares them based on the following fields: id, address, mangled_function, nodes, edges, size. I added `bytes_hash` and now I get the function in question reported as a partial match with a ratio of 0.99, which is what I was expecting.

So it seems like as long as two functions have the same name, address, size, and control flow they get reported as 100% equal even though the instructions in the functions could have changed? Is this intended behavior or a bug?

**Comment by joxeankoret** [comment]
>So it seems like as long as two functions have the same name, address, size, and control flow they get reported as 100% equal even though the instructions in the functions could have changed? Is this intended behavior or a bug?

This is intended behaviour. But according to the very detailed report you made, it might be wrong. I'm going to add the patch you did (adding `bytes_hash`) but, could you please share the two samples? (Or their hashes, and I would search them myself).

**Comment by grimdoomer** [comment]
I have attached the sample files and IDC scripts used to reproduce the IDA databases I had setup. You can load each .bin file as "PowerPC big-endian", use default memory layout settings, if asked analyze as 32-bit, use all default settings for IO ports, etc. Please let me know if you have any other questions or issues loading the samples.

![image](https://github.com/user-attachments/assets/59297f05-0a31-438e-b3c9-1a52723cc3c8)
![image](https://github.com/user-attachments/assets/bb1fa464-a37d-496c-810e-9f82753d9138)
![image](https://github.com/user-attachments/assets/d3f91cd1-8362-4047-919e-dbd22b749e39)
![image](https://github.com/user-attachments/assets/853127b3-53c1-4bfa-bb06-ff3f4985c977)
![image](https://github.com/user-attachments/assets/89d50ff3-5ff8-40cf-9b7a-246f44dd08c1)

[hv_images.zip](https://github.com/user-attachments/files/16927294/hv_images.zip)

**Comment by joxeankoret** [comment]
Bug fixed locally, waiting for all the tests to pass. Thanks a lot!

**Comment by karpiyon** [comment]
can you paste a fix for where to add "bytes_hash"?
I ma having the same issue.
I set it here nut it still did not find mismatches:
      fields = "id, address, mangled_function, nodes, edges, size, bytes_hash"

**Comment by joxeankoret** [comment]
The patch is live so you don't need to add it anywhere, it should work. Can you please tell me what is the exact issue you are having @karpiyon?

**Comment by karpiyon** [comment]
I am comparing 2, rather large sql saved files (300-400MB).
I know that some function are different yet they are reported as %100 equal.
e.g. a function may be identical apart from 1 byte, e.g. one function has JNE and the other JMP. 
When I open those %100 functions, which i know are different, I do see the difference.
In the reports which open I only see "Best" and "Unmatched" functions.
All to "Best" are shown as identical and there are no "Partial" functions.

**Comment by joxeankoret** [comment]
OK, now, are you sure you are using the latest version from git? Because this is something that I fixed time ago:

https://github.com/joxeankoret/diaphora/commit/7ff7058a1ab139c9d5ed91df5019436f91652506

**Comment by karpiyon** [comment]
I am downloading the repository directly from github.
I'll verify this in a couple of ours and report back.

**Comment by karpiyon** [comment]
I was NOT using the latest version.
It is working now.

BTW, why are thee lines look different? The only difference is the comment. can i ignore comments?

![image](https://github.com/user-attachments/assets/d4840aab-3fd5-4305-a109-d89ffcf9927c)

**Comment by joxeankoret** [comment]
I'm afraid this is a limitation of the current diffing UI engine. Sorry, but no, there is no option right now for ignoring comments.

**Comment by karpiyon** [comment]
Can't you and an option to ignore comments and then delete/remove them in the .sqlite file you are saving?

**Comment by joxeankoret** [comment]
I will take a look to that option
