### ISSUE TITLE
Adjust IDApython 9.0 

### ISSUE THREAD

**Issue by breaking153** [joxeankoret/diaphora#314]
Using IDA Python 9.0:
![image](https://github.com/user-attachments/assets/f8b36cd2-49d5-4f07-a279-54cb0ed52e60)
Using IDA Python 7.7:
![image](https://github.com/user-attachments/assets/4fd29a99-ee2a-4f73-8543-c9d218766a36)

**Comment by joxeankoret** [comment]
You are using an old version, because it's ported to IDA 9.0 since beta 1. Can you please double check?
