### ISSUE TITLE
Hung on diffing databases

### ISSUE THREAD

**Issue by Chrys4lisfag** [joxeankoret/diaphora#316]
![image](https://github.com/user-attachments/assets/2068d49b-ea18-4f83-bde5-47b5ca63c287)
Been stuck here for 8hrs when comparing large databases. Tried two times. Both times the same.

IDA 7.7 pro
128 RAM, Ryzen 5 3600
Windows Server 22
2gb each db.
Diff settings - default.

Do I need to test or send anything to you?

**Comment by Chrys4lisfag** [comment]
Used version from the latest commit: https://github.com/joxeankoret/diaphora/commit/7ff7058a1ab139c9d5ed91df5019436f91652506

**Comment by joxeankoret** [comment]
IDA 7.7 is a terribly old version. If you are using the latest git version of Diaphora you are using a version with all the known workaround already applied. As so, I'm afraid I can only give you two options:

 * [Diff in batch mode](https://github.com/joxeankoret/diaphora/wiki/How-can-I-automate-the-diffing-process%3F#diffing-in-batch-mode) without using IDA (because it's 99% sure an IDA bug) and then load the stored results using [`diaphora_load.py`](https://github.com/joxeankoret/diaphora/blob/master/diaphora_load.py). 
 * Upgrade your IDA version to a more recent version.

**Comment by Chrys4lisfag** [comment]
> IDA 7.7 is a terribly old version. If you are using the latest git version of Diaphora you are using a version with all the known workarounds already applied. As so, I'm afraid I can only give you two options:
> 
> * [Diff in batch mode](https://github.com/joxeankoret/diaphora/wiki/How-can-I-automate-the-diffing-process%3F#diffing-in-batch-mode) without using IDA (because it's 99% sure an IDA bug) and then load the stored results using [`diaphora_load.py`](https://github.com/joxeankoret/diaphora/blob/master/diaphora_load.py).
> * Upgrade your IDA version to a more recent version.
> 
> If diffing in batch mode, however, doesn't work, please tell me as this is a Diaphora bug.

Is 9.0 fully supported ATM or need to wait?

**Comment by joxeankoret** [comment]
Yes, IDA 9.0 is supported since beta 1.

**Comment by Chrys4lisfag** [comment]
![image](https://github.com/user-attachments/assets/e0f573ac-3a1e-463a-be1f-10d1b96a8b02)
Currently been stuck here for 1.5hrs, will wait more and test for 9.0 a bit later

**Comment by Chrys4lisfag** [comment]
Yeah. still stuck for 7.7.... Can I use diaphora dbs but compare from 9.0? Or is it better to regenerate them? Currently I launched diff for prev dbs generated by 7.7

**Comment by Chrys4lisfag** [comment]
![image](https://github.com/user-attachments/assets/538be820-109e-48c2-9a1a-90dbc6fd50cb)
Been stuck again in IDA 9.0, used sql`s databases from ida 7.0. Should I regenerate them?

**Comment by Chrys4lisfag** [comment]
After the whole night the console log hasn't moved a line, still stuck at INFO: Finding with heuristic 'Same constants related matches'.

If I need to test anything, just tell me

**Comment by joxeankoret** [comment]
Uhm... if you are testing it from outside IDA, then the problem might be with the SQLite databases (and no, no worries, you don't need to recreate them with a newer version of IDA or anything, it doesn't matter). What is happening here is that the last part (the method in diaphora.py named `find_related_matches()`) is taking too long. This method performs continuous iterations until no new iteration finds any new rows. Could you please try adding the following code here: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L3833

```
            iteration += 1
            if iteration >= 3:
              break
```

Right now, this process performs as much iterations as it requires as long as it finds at least one more new match. With this limitation I'm telling you to add, it won't continue after the 3rd iteration.

**Comment by Chrys4lisfag** [comment]
> Uhm... if you are testing it from outside IDA, then the problem might be with the SQLite databases (and no, no worries, you don't need to recreate them with a newer version of IDA or anything, it doesn't matter). What is happening here is that the last part (the method in diaphora.py named `find_related_matches()`) is taking too long. This method performs continuous iterations until no new iteration finds any new rows. Could you please try adding the following code here: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L3833
> 
> ```
>             iteration += 1
>             if iteration >= 3:
>               break
> ```
> 
> Right now, this process performs as much iterations as it requires as long as it finds at least one more new match. With this limitation I'm telling you to add, it won't continue after the 3rd iteration.

Edited and launched the diff. Will inform you about the results later.

**Comment by joxeankoret** [comment]
Thank you!

**Comment by Chrys4lisfag** [comment]
> Thank you!

It didn't help...
![image](https://github.com/user-attachments/assets/09994d85-671d-4c4b-829e-94ba2bed3f43)

**Comment by Chrys4lisfag** [comment]
If turning off slow DIFFING_ENABLE_SLOW_HEURISTICS, it gets stuck at 'Related compilation unit' now.

**Comment by joxeankoret** [comment]
Uhm... it sounds rather weird. I'm sure it would finish, but I don't know when, to be honest. Try changing `if iteration >= 3` to 1 instead of 3. It will end. Turning off `DIFFING_ENABLE_SLOW_HEURISTICS` won't really do anything here, as `find_related_matches()` is not affected by that flag.

**Comment by Chrys4lisfag** [comment]
> Uhm... it sounds rather weird. I'm sure it would finish, but I don't know when, to be honest. Try changing `if iteration >= 3` to 1 instead of 3. It will end. Turning off `DIFFING_ENABLE_SLOW_HEURISTICS` won't really do anything here, as `find_related_matches()` is not affected by that flag.

When I first encountered this issue, I left the comparison for 2 days...
But ok, I changed to 1 iter now and started again.

**Comment by Chrys4lisfag** [comment]
It worked with 1 iter
