### ISSUE TITLE
ida 9 plugin error 

### ISSUE THREAD

**Issue by breaking153** [joxeankoret/diaphora#318]
needs ida 9 compatible update!!
here is the port guide to ida 9.
https://web.archive.org/web/20240810011600/https://out5.hex-rays.com/beta90_6ba923/idapython_porting_guide.md
![image](https://github.com/user-attachments/assets/39cef21c-24c3-476e-b28e-44ad2f7553df)

**Comment by joxeankoret** [comment]
Have you updated your Diaphora version? Because IDA 9.0 was supported since beta 1. Please try with the github version.

**Comment by joxeankoret** [comment]
What error are you getting @Accord96 ?

**Comment by Accord96** [comment]
exactly like the one in the screenshot above

**Comment by joxeankoret** [comment]
Are you using the version from git or the release?

**Comment by Accord96** [comment]
I tried this way and that

**Comment by joxeankoret** [comment]
Can you please verify that you have this function in your version of Diaphora?
https://github.com/joxeankoret/diaphora/blob/master/diaphora_ida.py#L3315

**Comment by Accord96** [comment]
Sorry, it's my mistake, I accidentally specified the path in the config of a non-latest version

**Comment by joxeankoret** [comment]
No worries. Feel free to reopen if you have problems with the current version.
