### ISSUE TITLE
Confusing description of "export microcode and basic blocks" option

### ISSUE THREAD

**Issue by vient** [joxeankoret/diaphora#319]
https://github.com/joxeankoret/diaphora/blob/7ff7058a1ab139c9d5ed91df5019436f91652506/diaphora_ida.py#L723
Option is name "export microcode ..." which means it will do something if checked. Help for it says "enable this option to disable exporting microcode" though. From the code it seems that help message is wrong here.

**Comment by joxeankoret** [comment]
Oops, nice catch, thanks for reporting!
