### ISSUE TITLE
Function size issue  in "read_function()"

### ISSUE THREAD

**Issue by BigJim** [joxeankoret/diaphora#32]
In "read_function()" the function size from the calculation "size = func.endEA - func.startEA" can be wrong.  Where most of the time, depending on the target, a function body will be in a contiguous space, 
it's not guaranteed to always be that way.  Function blocks can be split up and jump over the following function etc.  For an extreme  example see a Windows system DLL like "kernel32.dll".

Also since we are walking over blocks we'll be occasionally skipping unused alignment  bytes, etc (that are jumped over). You don't want them counted in the size.
To get the correct size you have to sum the size of each block as you enumerate them.

**Comment by joxeankoret** [comment]
That's right, I will change it to really calculate the true size (using the size of each instruction). Thanks for pointing out this!

**Comment by joxeankoret** [comment]
Should be fixed with 08552b90eb47a44028b0932dfe66ff8902ead2be

**Comment by joxeankoret** [comment]
Closing.

**Comment by joxeankoret** [comment]
Closing.
