### ISSUE TITLE
Show RVAs in the assembly diff

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#33]

**Comment by Rumata888** [comment]
joxean, I added this in my diaphora, would you like me to uplod this in some way?

**Comment by joxeankoret** [comment]
Yes, please. Send me a pull request if that's not a problem.

**Comment by Rumata888** [comment]
git pull https://github.com/Rumata888/diaphora master

**Comment by Rumata888** [comment]
Though there is one log instruction for now that I haven't cleaned up yet

**Comment by Rumata888** [comment]
I deleted unnecessary logging

**Comment by Rumata888** [comment]
Will you merge it into your main branch?

**Comment by joxeankoret** [comment]
Sorry, too much work. I will take a look today or tomorrow.

**Comment by joxeankoret** [comment]
OK, sorry. I verified it: the patch is not what people asked me. Some people asked to show the RVA in each line of the assembly in the plain assembly diff text-view.

**Comment by joxeankoret** [comment]
Is it still relevant?
