### ISSUE TITLE
Error Running diaphora.py Script

### ISSUE THREAD

**Issue by S1LM4R** [joxeankoret/diaphora#35]
Receiving an error "No IDA database opened or no function in the database. Please open an IDA database.." when running File->Script File->diaphora.py as stated in the tutorial PDF.

**Comment by joxeankoret** [comment]
The obvious answer: do you have any IDA database opened?

**Comment by S1LM4R** [comment]
Omg.  I'm an idiot.  I'll delete.  Sorry Jox

**Comment by joxeankoret** [comment]
No worries :)
