### ISSUE TITLE
Maybe there should be a way to turn on and off different heuristics?

### ISSUE THREAD

**Issue by Rumata888** [joxeankoret/diaphora#38]
Diffing 2 win32k.sys drivers didn't finish after 12 hours. Got stuck on Fuzzy Ast Hash.

**Comment by Rumata888** [comment]
Checked 3 times.Rebooted. Reinstalled IDA. Checked again.

**Comment by joxeankoret** [comment]
Sorry for the late response, I have been out for holidays. Reinstalling IDA is not going to help. Un-check the mark for "Enable slow heuristics". If it doesn't help, please tell! In future versions, I'm planning to let the reverser enable/disable which heuristics should be applied.
