### ISSUE TITLE
IDA's "show casts" greatly affects pseudocode diffing

### ISSUE THREAD

**Issue by mspublic** [joxeankoret/diaphora#39]
If the Hexrays pseudo code option "show casts" is enabled on one DB but not the other it greatly affects Diaphora's ability to properly diff pseudo code. Is there a way to force the export to always choose one or the other?

**Comment by joxeankoret** [comment]
This is a known issue... And, no, unfortunately there is no "official" way I know. I asked Ilfak in the past how to enable/disable "Show casts" programmatically an he told me there is no official way yet :/

**Comment by joxeankoret** [comment]
Unless the Hex-Rays guys offer a way to disable/enable castings in pseudo-code, I'm closing it for now, as there is nothing we can do :( I will reopen it myself when a fix is possible. Probably, with a future IDA version.
