### ISSUE TITLE
Cannot select multiple functions in Match View List

### ISSUE THREAD

**Issue by ionescu007** [joxeankoret/diaphora#4]
Hi,

It would be really nice to be able to select multiple items in the partial/full/unmatched view, especially to be able to "multi-import" functions. Right now, the only choice is import EVERYTHING or import one function. It's extremely annoying to right-click on each function one by one by one... ;-)

**Comment by joxeankoret** [comment]
Thanks Alex, I will add it soon.

**Comment by joxeankoret** [comment]
I have to ask the Hex-Rays guys because there is no "selection" like member neither the "OnSelectionChange" event works.

**Comment by ionescu007** [comment]
Other plugins can do it, so I know there must be a way :)

**Comment by joxeankoret** [comment]
https://www.hex-rays.com/forum/viewtopic.php?f=6&t=3815&p=16027#p16027

**Comment by ionescu007** [comment]
Wow, I can't believe they broke such a simple thing. Hope they fix it :)

In the mean time, do you think you could add accelarator/shortcut keys to some of the menu items. For example, if pressing 'i' would import the currently selected function, then it would be a lot faster to just press "down arrow", "i", "down arrow", "i", etc. to quickly import a bunch of functions.

**Comment by joxeankoret** [comment]
It's half-fixed now. I can implement it for 6.7 and 6.8 (I'm beta testing it), but not for previous versions because AddCommand doesn't support shortcuts. Give me some days.

BTW: I have a fix, I think, for all the other bugs, but I'm still waiting for the right fix for some IDAPython bug from the Hex-Rays guys.

**Comment by joxeankoret** [comment]
Support added with 9eb60b7bf95f7a659b8f3d29a83e2d31d6bd2b74. You will need to ask at support@hex-rays.com for the fix for 6.7 versions or wait a few days for 6.8.
