### ISSUE TITLE
Feature Request: Ability to rename output tabs.

### ISSUE THREAD

**Issue by nanotechz9l** [joxeankoret/diaphora#44]
It would be nice to be able to rename the "Unmatched in primary", and "Unmatched in secondary" tabs.

That way it would be even easier to keep track of what is being worked on.

Thanks!

**Comment by joxeankoret** [comment]
I will think about adding a way to mark the functions as checked/unchecked.

**Comment by nanotechz9l** [comment]
Understood thanks!

**Comment by joxeankoret** [comment]
Only one person shown interest on it. I'm closing it for now.
