### ISSUE TITLE
Feature Request: Diaphora GUI closes when selecting .idb file.

### ISSUE THREAD

**Issue by nanotechz9l** [joxeankoret/diaphora#45]
Currently when selecting an .idb file by accident to diff against the Diaphora GUI throws a pop up error and closes. Accidents happen and it would be more efficient if instead of closing the UI it would just pop up an error then revert back to the Diaphora UI. This will save time needed to manually repeat the process.

[ Reproduce ]
Open an .idb file at any either the "Export IDA db to sqlite" or "Sqlite db to diff" fields. GUI pops up an error and closes the Diaphora UI.

**Comment by joxeankoret** [comment]
OK, I will implement this.

**Comment by nanotechz9l** [comment]
Great thank you!

**Comment by joxeankoret** [comment]
I have been playing with this. I don't think it's really needed as it makes the code a bit convoluted and the benefit it offers is minimal. Sorry, I will not fix it.
