### ISSUE TITLE
Bad Imports in IDA 6.9

### ISSUE THREAD

**Issue by tmr232** [joxeankoret/diaphora#48]
Currently, the code checks for the presence of `PySide`, and only uses `PyQt5` if it does not exist.
This causes issues when `PySide` is installed for the system, and not used by IDA. In those cases - Diaphora might import `PySide` instead of `PyQt5` and fail.

**Comment by joxeankoret** [comment]
Thanks for pointing it out, will be fix tonight or tomorrow morning!

**Comment by joxeankoret** [comment]
Fixed with commit d02da14eb57a31349965f49cec060a5699aa41ab
