### ISSUE TITLE
Feature request: column "unmatches basic blocks count"

### ISSUE THREAD

**Issue by flyninja** [joxeankoret/diaphora#50]
Many functions fall into the table "partial matches" due to the change of the prototype, but no logic. Some fall into the "best matches", but have diverging criteria for different base blocks. "Ratio" is a column too vague evaluates, need an extra column to answer "yes" or "no" to the question whether two functions logically mismatched base blocks and how many of them. View all call-graph in "partial matches" for too long, and the "best matches" may miss an important diff.

**Comment by joxeankoret** [comment]
Sorry for taking that long. I added the columns "BBlock 1" and "BBlock 2" to the matches windows with commit afd716836cbd3db6254204f05374b6e19176b672
