### ISSUE TITLE
Unhandled MemoryError (IDA 64bit)

### ISSUE THREAD

**Issue by DaxxTrias** [joxeankoret/diaphora#51]
Hello,

I'm having a problem trying to diff some files in the 64bit IDA client with the latest svn of you're script. I've been paying attention to the working size of the ram and while thats always below 2gb reportedly, the temp file that gets used gets excessive of 23GB for the diff I'm doing. (The bin's are about 60mb each, the disasm file comes out to about 700mb each (with symbols))

I saw a relatively similar issue reported for the 32bit client that you implemented a fix for but the filer of the issue didn't respond back to you ( #30 ) I can only assume what I'm experiencing is related but not identical. I believe my problem stems from utilizing the symbols attached to the extremely large bin. Without the symbols the IDA disasm file only reaches about 200mb, but with symbols its excess of 700mb. The error I'm getting occurs with or without the following recommended options being used:
_Export only non-IDA generated functions_
_Do not export instructions and basic blocks_

If you want I can upload the examples, however they're freaking huge. If you were to get both files for comparison it would be an upload of about 500mb total (2x 60mb bin's, 2x 200mb pdb's)

Unfortunately this diffing process takes me 8+ hours and then fails with the following:

```
[Thu Feb 04 15:37:48 2016] Finding with heuristic 'Small names difference'
Error: 
Traceback (most recent call last):
  File "E:/NewDev/diaphora/diaphora.py", line 3743, in _diff_or_export
    bd.diff(opts.file_in)
  File "E:/NewDev/diaphora/diaphora.py", line 3580, in diff
    self.find_matches()
  File "E:/NewDev/diaphora/diaphora.py", line 3063, in find_matches
    self.search_small_differences(choose)
  File "E:/NewDev/diaphora/diaphora.py", line 2695, in search_small_differences
    rows = cur.fetchall()
MemoryError
```

**Comment by joxeankoret** [comment]
Uhm... complex bug. I think I have an idea to fix it...
BTW, thanks for the extensive report!

**Comment by joxeankoret** [comment]
Please, try with the following patch:

```
diff --git a/diaphora.py b/diaphora.py
index deff7eb..30831b0 100644
--- a/diaphora.py
+++ b/diaphora.py
@@ -98,6 +98,16 @@ You can disable it by un-checking the 'Do not export basic blocks<br>
 or instructions' option."""
 
 #-----------------------------------------------------------------------
+def result_iter(cursor, arraysize=1000):
+  'An iterator that uses fetchmany to keep memory usage down'
+  while True:
+    results = cursor.fetchmany(arraysize)
+    if not results:
+      break
+    for result in results:
+      yield result
+
+#-----------------------------------------------------------------------
 def log(msg):
   Message("[%s] %s\n" % (time.asctime(), msg))
 
@@ -956,7 +966,7 @@ class CBinDiff:
 
       sql = "select * from results"
       cur.execute(sql)
-      for row in cur.fetchall():
+      for row in result_iter(cur):
         if row["type"] == "best":
           choose = self.best_chooser
         elif row["type"] == "partial":
@@ -974,7 +984,7 @@ class CBinDiff:
       
       sql = "select * from unmatched"
       cur.execute(sql)
-      for row in cur.fetchall():
+      for row in result_iter(cur):
         if row["type"] == "primary":
           choose = self.unmatched_primary
         else:
@@ -1566,7 +1576,7 @@ class CBinDiff:
     cur = self.db_cursor()
     sql = "select type, name, value from diff.program_data where type in ('structure', 'struct', 'enum')"
     cur.execute(sql)
-    rows = cur.fetchall()
+    rows = result_iter(cur)
 
     new_rows = set()
     for row in rows:
@@ -1855,7 +1865,7 @@ class CBinDiff:
                order by bb.address asc""" % (db, db, db, db, db)
     cur.execute(sql, (ea1,))
     bb_blocks = {}
-    for row in cur.fetchall():
+    for row in result_iter(cur):
       bb_ea = str(int(row[0]))
       ins_ea = str(int(row[1]))
       mnem = row[2]
@@ -1886,7 +1896,7 @@ class CBinDiff:
                and f.address = ?
              order by 1 asc, 2 asc""" % (db, db, db, db, db, db)
     cur.execute(sql, (ea1, ))
-    rows = cur.fetchall()
+    rows = result_iter(cur)
 
     bb_relations = {}
     for row in rows:
@@ -2692,7 +2702,7 @@ class CBinDiff:
                  and f.cyclomatic_complexity = df.cyclomatic_complexity
                  and f.names != '[]'"""
     cur.execute(sql)
-    rows = cur.fetchall()
+    rows = result_iter(cur)
     for row in rows:
       ea = str(row[0])
       name1 = row[1]
```

**Comment by DaxxTrias** [comment]
Thanks for the swift response.

I applied the diff patch, verified the changes and am currently running the diffing process. In an effort to finish it faster so as to get you results quicker I am not running the unreliable / slow heuristic options in the hopes that this will finish faster then is usual in my experience.

Unless this fetchmany is significantly faster then fetchall, Its likely I won't have an update for you for many hours from now.

**Comment by joxeankoret** [comment]
I don't think it will be faster :( It will just don't crash. Hopefully. Let's see ::crosses fingers::

**Comment by DaxxTrias** [comment]
Well it took quite literally forever but the good news is it did not crash.

According to the timestamp entries it seems for it to run the entirety it took 32hours with the longest subroutines being _Finding unmatched functions_ (9hours), and _Small names difference_ (19 hours)

Still though you fixed the crash bug, thank you.

**Comment by joxeankoret** [comment]
Fortunately! Thanks a lot for the bug report, I will commit it to main soon. And I will do my best to make it faster. BTW, you're absolutely for sure the person who ran the biggest diff with Diaphora up to today.

**Comment by mspublic** [comment]
Out of curiosity - would running Diaphora in pypy result in a large speed increase?

**Comment by joxeankoret** [comment]
It would only be possible in case IDAPython is also ported to Pypy. Is not a problem totally exclusive to either Diaphora or Python, but to IDAPython.

**Comment by DaxxTrias** [comment]
For the sake of finalizing this I'm going to run 1 more diff without the recommended disables for large binaries:
Export only non-IDA generated functions
Do not export instructions and basic blocks

I expect hell to freeze over before it finishes (lol) but I'm hoping to confirm whether your fix will stand up against a full disasm rather then one that intentionally skips portions.

PS I wonder if you might be able to split the 2 subroutines I mentioned with the exceptionally long process times into 2 or more threads perhaps splitting their workload into sections and dispatching threads for those sections.

I'm by no means proficient with multithreading or even python, however I have a friend who created a project for me in python that executes commands which utilize lots of File IO across multiple threads for very specific conditions. 

Incase you are curious here is a snippet from the project I refer to. 
http://hastebin.com/yixiladove.py

**Comment by mspublic** [comment]
True. It is definitely not a Diaphora specific issue... Probably just manifests itself heavily in Diaphora due to there not being very many IDA python scripts with the complexity/load requirements of Diaphora. I guess the C plugin in BinDiff is where the speedup came from.

**Comment by DaxxTrias** [comment]
Addendum:

Trying to export the sqlite database for the same binary file that was used to do my previous disasm just kicked to me another error which I have not seen thus far. (However as stated in my previous comment this is my first attempt trying to do a full diff rather then a selective diff, by simply using the defaulted options)

I'm wondering if this could possibly be due to harddrive space although that doesn't seem plausible to me. During the diff phase sure I could potentially see it consuming the last of my space, but this is just the export phase. Previously my exports came out to about 2gb in size, factoring in the selected options change I wouldn't expect the process to even be capable of consuming the 100gb available on my drive however I'm including this hypothetical just incase.

[Sat Feb 06 17:38:45 2016] Cannot decompile 0x140f6de90: Decompilation failed: 
Error: 
Traceback (most recent call last):
  File "E:/NewDev/diaphora/diaphora.py", line 3742, in _diff_or_export
    bd.export()
  File "E:/NewDev/diaphora/diaphora.py", line 1546, in export
    self.do_export()
  File "E:/NewDev/diaphora/diaphora.py", line 1532, in do_export
    self.save_function(props)
  File "E:/NewDev/diaphora/diaphora.py", line 1376, in save_function
    cur.execute(sql, new_props)
MemoryError

**Comment by DaxxTrias** [comment]
Forgot to write back that aside from some of the dumps failing to export (as described above) the actual problem I originally reported has been fixed. Thank you very much for resolving it.

**Comment by joxeankoret** [comment]
Thanks! I will leave it open until I push a proper whole fix.

**Comment by joxeankoret** [comment]
With the last commits it should be working properly, so I'm closing. Feel free to re-open it it you have the same or related problems.
