### ISSUE TITLE
Trouble running

### ISSUE THREAD

**Issue by Avinem** [joxeankoret/diaphora#52]
Opening the script as described in the pdf resuslts in 

> Script Default snippet error: 1: Bad or ill-formed preprocessor command

Running on IDA 6.8.150423 (32-bit). Removing the `#!/usr/bin/python `directive results in a different error: 

> Function Declaration expected

**Comment by joxeankoret** [comment]
It looks to me like IDAPython is not working for you, as the errors look like IDC ones. Is IDAPython working?

**Comment by Avinem** [comment]
You're right, it seems my IDAPython broke after upgrading to 2.7.11 downgrading to the 2.7.6 supplied with the installer fixed it. Thank you.

**Comment by joxeankoret** [comment]
You're welcome!
