### ISSUE TITLE
Use of binexport for large DBs

### ISSUE THREAD

**Issue by mspublic** [joxeankoret/diaphora#53]
Now that binexport is opensource - what are your thoughts on potentially leveraging it? I know it adds a HUGE amount of dependencies... But it is very fast and fairly stable even for large databases. Maybe it can be an optional "plugin" for people who need the heavy lifting? Python takes a insanely long time to do exports of large DBs - and has its own host of issues like #51.

Just wanted to get your thoughts on the topic...

**Comment by joxeankoret** [comment]
I would need to take a look to it and determine if we can modify it in order to export to a format understood by Nightmare. I have been thinking over it already, but didn't have yet the time to check the source.

**Comment by joxeankoret** [comment]
With the commit e8ce91645b80d3e93f8ef72c53531adae6eb4a6a the export time have been reduced drastically, 6 times indeed. Should it be still considered? Either using BinExport (meh) or creating a C++ exporter?

**Comment by mspublic** [comment]
I haven't had time to compare the differences again between binexport/diaphora. With a 6x increase definitely would make a big difference. Maybe this could be set to low priority/filed under future ways to speed up performance?

**Comment by joxeankoret** [comment]
I agree.

**Comment by joxeankoret** [comment]
Closing this as I'm not going to use 3rd party code. However, I will try to make it faster. Although it's really complex.
