### ISSUE TITLE
[Question] add_matches_from_query_ratio function logic

### ISSUE THREAD

**Issue by lmolas-sadosky** [joxeankoret/diaphora#54]
Hi, I've been using diapohra (thanks for the tool by the way) and I'm having some doubts about how does the [`add_matches_from_query_ratio`][1] function work.

After computing the [similarity ratio][2], the [third if][3] compares it to a 5, which I'm guessing it's just a typo, with no impact because by that if the `r` is already under 0.5.

But what I'm not getting (and I'm probably missing something) is that whichever case is taken, even partial or unreliable, the names of the functions are registered as matched, adding them to `self.matched` sets. That means they will be skipped from any posterior match analysis, due to the [check][4] prior to the call of `check_ratio`. Even if the ratio was 0 (false positive from the heuristics) that function will not be considered in the future.

I actually stumbled upon this issue while trying to craft my own heuristic, which was very defective, causing many false positives, and this probably is not the case with the current heuristics of diaphora, but I think this possibility should be considered at least for the experimental ones.

Thanks,
Lucas

[1]: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L2544
[2]: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L2584
[3]: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L2593
[4]: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L2581

**Comment by joxeankoret** [comment]
Hi @lmolas-sadosky,

The functions ```add_matches_*``` are only called when there is a match and should not be called when there are results without matches. If you want to add your own heuristics, you should filter out invalid results before actually calling any of these functions.

For an example in which no such functions are called and the results are filtered you can take a look to this https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L2802 .

Perhaps I should add a little guide on how to add new heuristics.

Regards,
Joxean Koret

**Comment by lmolas-sadosky** [comment]
Yes that would be very helpful. Thanks for the clarification.

Lucas
