### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero, for small number of functions

### ISSUE THREAD

**Issue by lmolas-sadosky** [joxeankoret/diaphora#55]
Hi, when the number of functions to be exported is under 10, the division:

[`if i % (total_funcs/10) == 0:`][1]

is returning zero (for Python 2.x), causing the above error.

Lucas

[1]: https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L1535

**Comment by joxeankoret** [comment]
Thanks for the report! Bug fixed with commit 6045a9a3716b85900eaf6e99d9835aba550de463.
