### ISSUE TITLE
Diaphora does not import global variable names/symbols

### ISSUE THREAD

**Issue by ionescu007** [joxeankoret/diaphora#6]
When importing from one database with symbols, into another without symbols, global data variable names are not imported. This would greatly help with imports and reduce differences as well.

I believe that once a function has been declared to be a match of another function (by algorithm or by user), all global variables accessed by unknown function X should be renamed to the names as seen in function Y.

Please let me know if this makes sense.

**Comment by joxeankoret** [comment]
It makes a lot of sense. I will be adding it today.

**Comment by joxeankoret** [comment]
It isn't as easy as I thought. It will take some more time to add this feature.

**Comment by cexikitin** [comment]
Any ETA on when this can be implemented? I've got a ton of RTTI information in one version that has been removed in subsequent versions and porting these names over would be a big help.

**Comment by joxeankoret** [comment]
I'm currently working on this. An initial version for best matches and partial matches with full basic block matches should be available in 1 to 2 weeks.

**Comment by ionescu007** [comment]
Update? :)

**Comment by joxeankoret** [comment]
Finishing it. It works at instruction level (whole instructions are matched), now I need to do at basic block level too.

**Comment by joxeankoret** [comment]
Sorry for taking that long. Implemented with d0c14a1fdbef43408a5a3f5f9214b5ac81b8333b
