### ISSUE TITLE
Diffing strings?

### ISSUE THREAD

**Issue by fuzun** [joxeankoret/diaphora#60]
How can I diff strings?

**Comment by joxeankoret** [comment]
Uhm... what?

**Comment by fuzun** [comment]
Sorry for lack of information. I meant this:
IDA can export strings out of binary files. Consider this:
A patch arrived and some strings are changed some are deleted and some are added. (Maybe you can track changed strings with xref ?)
So how can I properly diff these two binaries specifically for strings.

**Comment by joxeankoret** [comment]
Diffing the strings is trivial. But I never considered it any useful. Is it?

**Comment by fuzun** [comment]
It helps tracking. Some binaries have more than 50000 functions and 10000 strings. And when a patch arrives, a lot of function get changed (even though you check relaxed diffing option, you need to check almost %80 of functions) . This case, if I look for newly added strings, I can easily find what implemented.

Or maybe I am missing some point?

**Comment by joxeankoret** [comment]
Uhm... what about a tab with matched, fuzzy matched and new strings found? Would it be useful?

**Comment by fuzun** [comment]
I think it would be good. But it would be excellent if it can track edited strings (Do you mean this with fuzzy match?). Can't this be done by looking where the string is used (xref ?) and then looking matches / partial matches ?

And diffing imports, exports, enums, structures alongside with strings would be cool. Especially imports may give a hint if something new added.

**Comment by joxeankoret** [comment]
Uhm... this is for video-games, right? I think I could do the following:

 * Get all the strings *with* XREFs in both binaries.
 * Diff these strings that are longer than $size characters.
 * Track equal, similar, new and deleted strings.

Regarding diffing imports, exports, enums, structures, etc... This is a lot of extra-work. I don't see how it can be useful to diff enums and structures when this information is not available in most cases, only when there are full debugging symbols. 

I will surely implement strings diffing but I can't see any real usage of structs/enums diffing. Can you give me some use-case?

**Comment by fuzun** [comment]
Yes.
I think implementation of diffing enums and structures won't worth the time you would spend, as you say this information is not available in most cases. For example in a 12 mb pure code binary, which contains 38000~ functions has 0 enums and only 5-10 structures according to IDA. It is not much needed.

But diffing imports and exports may make diffing easier. I don't think this will need much time because there is no such thing as changed imports or exports. It needs to track only removed and added.

**Comment by joxeankoret** [comment]
OK, give me some time.

**Comment by joxeankoret** [comment]
Oh, BTW: I'll surely implement also the imports/exports diff. However, consider that the import table doesn't really say, with many compilers/languages, that such an import is used at all. Also, it doesn't mean that a non (statically) imported function is not used: it can be dynamically resolved (dlopen+dlsym or LoadLbrary+GetProcAddress). I see a limited usage for it.

**Comment by fuzun** [comment]
Hmm I don't work with many languages but C++ and C. So I can't say anything about this. But in my case, IDA shows CODE XREF and when I seek into that, I can find where it is used.

And yeah it is limited but I don't think the loadlibrary method is a standard. In general, Malware producers and cheat makers use them.

**Comment by joxeankoret** [comment]
Pascal (Delphi or FPC) as well as GO, to put some samples, do that. Also, various functions across Windows versions are implemented in different DLLs or the API changed in this or that Windows version. Indeed, even Windows own components, do that.

If we talk about malware: that's even worst.

**Comment by fuzun** [comment]
Hmm, but should not it be IDA's problem? Diaphora is just a differ plugin, it just parses information what it gets from a main application like ida.

I think you should implement it if it won't take much time and then put a messagebox which contains information regarding this situation if user checks the checkbox.

It is very situationary but it may help a lot in specific situations, like experimental features of diaphora.

**Comment by mspublic** [comment]
so just throwing this in - but rizzo does have some basic string diff/matching - https://github.com/devttys0/ida/blob/master/plugins/rizzo/rizzo.py

Actually found it to be pretty useful as part of general diffing

**Comment by fuzun** [comment]
It looks like a good plugin - will check. It would definitely help implementations on this plugin.

**Comment by joxeankoret** [comment]
With a bit of luck, the strings diffing part, as well as the import/exports part, will be finished by this week.

**Comment by fuzun** [comment]
Thank you!

Will selection sqlite file dialog be fixed? (Can not see or select any sqlite files because of extension not added to extension list)
