### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by rafalsk** [joxeankoret/diaphora#65]
uuu.. I got dissapointed

I was exporting info regarding a 50MB exe file. 121k functions.
got an out of memory error after 2-3 hours. 16GB of ram.

estimated time on fix?

**Comment by joeleong** [comment]
Out of curiosity did you try the options mentioned in the help pdf? 

> 
> **Diffing huge databases (or exporting smaller .SQLite databases)**
>
> Some IDA databases can be huge: for example, IDA databases for firmware images or IDA databases for >100MB binaries. In such cases, exporting and diffing big databases takes a lot of time and space. In order to make it a bit faster and requiring less disk space to store the .sqlite databases that Diaphora uses the following new options were added in the last release candidate:
> * Export only non-IDA generated functions. It will only export the functions that are not IDA's auto-generated names, thus, exporting only the functions for which we have symbols or we already assigned a name.
> * Do not export instructions and basic blocks. It will export everything about the functions but will not export basic blocks, basic block's relationships or the instructions of all functions. It results in less export time as well as in significantly smaller SQLite databases.
>

**Comment by joxeankoret** [comment]
Hi @rafalsk,

If you could provide an IDB or binary I could provide an estimated time on a fix, if appropriate. Without a binary or IDB to test it out, I cannot say anything because I don't even know how to reproduce (it doesn't happen in my testing machines with even bigger databases).

**Comment by rafalsk** [comment]
Hello,

Yes, I can provide you with an IDB, as well as, binary. the binary
is around 50MB, whereas IDB is of 800mb in size. please provide an email
adress where I can provide you with appropriate links.

Regards,
Rafal

W dniu poniedziałek, 3 października 2016 Joxean <notifications@github.com>
napisał(a):

**Comment by rafalsk** [comment]
I am not sure but from what I recall the secind option was automatically
checked when Diaphora detected size of the file and I left it as it was.



W dniu poniedziałek, 3 października 2016 joeleong <notifications@github.com>
napisał(a):

**Comment by joxeankoret** [comment]
Awesome! You can find my PGP key as well as contact details here: http://joxeankoret.com/contact.html

**Comment by joxeankoret** [comment]
@rafalsk, by default Diaphora checks if the database is too big and select/deselect appropriate options. So, yeah, it would be a bug.

**Comment by rafalsk** [comment]
Ok, I shall provide you with links soon

W dniu poniedziałek, 3 października 2016 Joxean <notifications@github.com>
napisał(a):
