### ISSUE TITLE
Assumed til path

### ISSUE THREAD

**Issue by melomac** [joxeankoret/diaphora#68]
Hi

I noticed several times in the past that `diaphora` would raise an exception if the `.til` file was not located at the same place than the `.idb` file.

```
  def get_til_names(self):
    idb_path = GetIdbPath()
    filename, ext = os.path.splitext(idb_path)
    til_path = "%s.til" % filename
```

Problem is, if user decide to override `WORKDIR` setting in `idauser.cfg`, then it won't work.

```
WORKDIR                 = "/far/far/away/from/idb"            // Work direcrtory. IDA will create
                                    // temporary database files there.
                                    // Set to a directory on a separate disk
                                    // to improve open/close performance
                                    // of huge databases.
```

I digged around but wasn't able to find an easy way to get the real `.til` file path, so I am escalating the issue to the community.

Many thanks for `diaphora`.

**Comment by joxeankoret** [comment]
I honestly don't know how to do that. Closing for now.
