### ISSUE TITLE
Convert i64 to SQLite with cmd line

### ISSUE THREAD

**Issue by gooby482** [joxeankoret/diaphora#69]
Can you convert i64 files to SQLite files without having to go the IDA's GUI? I want to write a script that converts several hundred files via command line but I don't think your script supports my use case.

**Comment by joxeankoret** [comment]
It cannot convert from .i64/.idb to SQLite. It, however, can export to an unified format databases from IDA 32 (.idb) and IDA 64 (.i64).

**Comment by gooby482** [comment]
I was opening the unified format database file with SQLite3; I apologize for the confusion. Does this tool allow users to export unified format databases from .idb or i64 files via command line?

**Comment by joxeankoret** [comment]
Sorry for taking that long, I missed this one. Yes, you can export in batch mode:

```
$ idaq/idaq64 -A -B -S/full/path/to/diaphora.py /path/to/your/binary
```

**Comment by SagiUziel** [comment]
איל
