### ISSUE TITLE
Pseudocode comments not copied

### ISSUE THREAD

**Issue by skintigh** [joxeankoret/diaphora#73]
Comments made in the body of decompiled pseudocode are not copied, only repeatable function comments are.

**Comment by joxeankoret** [comment]
I'm not porting yet the pseudo-code comments. I will take a look into it. Thanks for reporting!

**Comment by joxeankoret** [comment]
Working on it. Should be available by this week.

**Comment by joxeankoret** [comment]
Implemented!
