### ISSUE TITLE
Bad or ill-formed preprocessor command

### ISSUE THREAD

**Issue by BullyWiiPlaza** [joxeankoret/diaphora#79]
Using IDA v6.8:
When I try to run the `diaphora.py` script it returns the following warning in the `Output` window:
`Script Default snippet error: 1: Bad or ill-formed preprocessor command`
I checked my Python installation and I have Python `2.7.6` installed like in [this](https://github.com/joxeankoret/diaphora/issues/52) issue but it didn't help. I also copied the `Python` folder from [here](https://github.com/idapython/src) into my `IDA Pro` installation directory. Same problem.

Using IDA v6.6:
Crashes when loading the script.
`IDA has encountered a problem. It is recommended to save your work and restart IDA...`

**Comment by joxeankoret** [comment]
Hi! It's definitely a problem with your IDAPython installation. Do you see a Python prompt at the bottom of the IDA window? If you only see an IDC one, there is some problem with your IDAPython installation.

As for IDA 6.6, I don't support it anymore. Sorry.

**Comment by BullyWiiPlaza** [comment]
Yeah, IDAPython is not available but I'm not sure how to fix that...

**Comment by joxeankoret** [comment]
Use the Python installer that comes with the IDA installer. If you're on Linux, you might need to install some libraries before: http://www.hexblog.com/?p=1048

**Comment by songbiaoself** [comment]
read ida dir `README_python3.txt` file can resolve this problem
