### ISSUE TITLE
When importing one function after the other, eventually it stops working

### ISSUE THREAD

**Issue by ionescu007** [joxeankoret/diaphora#8]
After right-click "Import one function" a few times, on a sequence of functions, it eventually stops actually importing the function.

When this bug happens, also double-clicking on a function shows this error:

OnSelectLine Wrong number or type of arguments for overloaded function 'jumpto'.
  Possible C/C++ prototypes are:
    jumpto(ea_t,int,int)
    jumpto(TCustomControl *,place_t *,int,int)

After the error is shown once, double-clicking again on a new function now works, and right-click "Import one function" works again.

Looks like an issue managing UI/selection state...

**Comment by joxeankoret** [comment]
I know why is it failing, will be fixed today.

**Comment by joxeankoret** [comment]
Should be fixed with 9eb60b7bf95f7a659b8f3d29a83e2d31d6bd2b74
