### ISSUE TITLE
Random Idea: diaphora as code similarity finder? [MULTI-DB]

### ISSUE THREAD

**Issue by mak** [joxeankoret/diaphora#82]
I'm getting tired of re-revering things, especially small semi-important function from various shitty malware.
While diffing is super helpful and diaphora is great tool i'm missing 
some centralized db that will hold all my functions and allows me to import types, names and other stuff into my working db - think like [crowd.re](https://recon.cx/2012/schedule/attachments/51_recon-crowdre-final-120621174609-phpapp02.pdf)  - without knowing exactly what to diff against? 

My normal approach is, when i'm missing something i start to code it - bu here i think i might be out my depth,  and using all methods in diaphora to find potential matches seems like a natural extension of it
First thing required will be to rewrite `diaphora.py` to be more server like thing and move sqlite into some real db ;]

I'm happy to roll up my sleeves and work on it, but firstly would like to ask first  if this is a good idea?  or the amount of heuristics is too much for such task and i should focus on building something that will rely on only few of them?

cheers,
mak

**Comment by joxeankoret** [comment]
This is one of the ideas that I'm working on. I expect to be working on it "soon", but I don't think it will make for this year.

**Comment by mak** [comment]
Hmm my application is to find out what changed in malware protocols and such and apply them to our tool so time is quite important factor;]

Can you elaborate on which 3-4 specific hashes/heuristics you have in mind? 
I'll try to put some effort into in in next moths 

cheers,
mak

**Comment by joxeankoret** [comment]
Take a look to this: https://github.com/joxeankoret/maltindex/blob/master/doc/malware_indexing.pdf
