### ISSUE TITLE
import_instruction_level algorithm issue

### ISSUE THREAD

**Issue by AGG2017** [joxeankoret/diaphora#84]
[test.zip](https://github.com/joxeankoret/diaphora/files/1339163/test.zip)
It expects a difference as simple "- +" lines to work properly. But if in the assembly code there are two or more lines in a raw that need to be fixed then it results as "- - + +" and the variables change_line and to_line cannot hold this type of result because it is a list of lines, not a single line and it becomes a big mess after the import is processed. Take a look of the example test file provided.

**Comment by joxeankoret** [comment]
Thanks for the samples! I will check what's going on wrong.

**Comment by AGG2017** [comment]
[HERE](https://github.com/AGG2017/diaphora) I created a temporary solution for myself until waiting an official fix. It is not optimized but it works well tested on a huge set of databases. I'm working with exotic MCUs and because there is no decompiler available I must rely only on comparing the assembly code. So it is very important to be able to transfer properly the functions, data names and comments relations from the previous work.

**Comment by AGG2017** [comment]
[test2.zip](https://github.com/joxeankoret/diaphora/files/1344586/test2.zip)
Additional problem in import_instruction_level is that difflib.ndiff does not work well when there are a lot of comments in the assembly. Check the output in the provided test code with a real world function example.
TEST1: with comments removed ndiff works as expected (but no comments are imported)
TEST2: with comments ndiff goes out of sync (and the result is only a few comments imported)
I have no idea how to fix that. I need the comments to be imported but sometimes they create additional problem to ndiff to describe properly the changed lines and as result some of the data names are missing in addition to some of the missing comments. One option is to just remove the comments before the call of ndiff and then restore them before calling import_instruction.

**Comment by joxeankoret** [comment]
Thanks for all the research and patches! I will try to fix it tomorrow morning but, if I don't have it for that time, I will not be able to work on it until Monday, sorry.

**Comment by AGG2017** [comment]
Don't worry, take your time. It is not urgent at all. I already have a temporary solution that is good enough for me. Just wanted to mention this problem with more details in order to be properly solved in some of the next versions. Thanks!

**Comment by AGG2017** [comment]
[test3.zip](https://github.com/joxeankoret/diaphora/files/1345709/test3.zip)
FYI: Yes, difflib.unified_diff is the way to go. You can check test3 and it works exactly as expected. Without comments there is no issue to find properly all differences and by using the provided info for the source line numbers we can restore the comments from the original lists. This solution looks good so far with all the functions I tested.

**Comment by AGG2017** [comment]
I still have some problems importing the comments related to an issue with the same function. After many tests it appears that only one comment can be imported for a specific assembly line. So if you have two or more equal asm lines in a function but with different comments only one of them will accept one of the imported comments and there is no guarantee it will be the right one: it depends of their address order. The rest of the comments are ignored. After analyzing of your code it looks the problem is with the used dictionaries import_syms and matched_syms. They collect the parameters of all different asm lines but because the key is the asm line by itself as result the same one are overlapped. That is enough to properly handle the function and data names but not the comments. It needs much more work for me to find a solution.

**Comment by AGG2017** [comment]
Now everything looks good related to importing functions, data names and comments except the import of user defined labels inside the functions. It can be done much better but this is pretty good for me. To fix the import of user defined labels will be my last attempt to finalize the import. Sorry to bother you with so many problems but I think the import function will be important to be better implemented for many users.

**Comment by AGG2017** [comment]
Unfortunately I'm not able to import completely the user defined labels with the current database structure. In the table instructions the label name is missing as information. Even if I export all arguments that refer to  an address with a name this will restore only labels with references but not the one defined to better understand the logic without any references to them. We must better use the comments.

**Comment by joxeankoret** [comment]
I will need a few days to correctly fix this (too much work, sorry)

**Comment by joxeankoret** [comment]
I will need some more days, sorry :/

**Comment by joxeankoret** [comment]
Still, I will need more time. Sorry for taking so long :/

**Comment by joxeankoret** [comment]
I believe I have a good patch for it that I have been coding during these days. If someone could send me binary files and/or databases where this behaviour can be reproduced so I can test my patches, I would be very thankful.

**Comment by joxeankoret** [comment]
Another option in case you don't want or you can't share binaries or databases: send me a message through whatever method you prefer and I will send you a ZIP via e-mail with the #Diaphora source with the latest patches applies so you can test it by yourself.
