### ISSUE TITLE
issue in add_matches_from_query_ratio()

### ISSUE THREAD

**Issue by huammmm1** [joxeankoret/diaphora#87]
when the function compares possible values of r,

conditional statement for elif is as follows. (line 1165 in diaphora.py)

"r < 5 and unreliable is not None:"

but, isn't it right to change it like this?

r < 0.5 and unreliable is not None: 

maybe it is typo or intended?

**Comment by joxeankoret** [comment]
You're right, that was a typo. Thanks a lot!
