### ISSUE TITLE
diaphora/diaphora.py: cannot import name md5

### ISSUE THREAD

**Issue by redirus** [joxeankoret/diaphora#88]
error happened when I tried to execute the script diaphora.py in ubuntu 16.04
$ ldd _hashlib.so 
	linux-gate.so.1 =>  (0xf7750000)
	libssl.so.0.9.8 => not found
	libcrypto.so.0.9.8 => not found
	libpython2.7.so.1.0 => /usr/lib/i386-linux-gnu/libpython2.7.so.1.0 (0xf738e000)

$ sudo apt-get install libssl0.9.8:i386 libpython2.7:i386 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libssl0.9.8-dbg:i386' for regex 'libssl0.9.8'

**Comment by redirus** [comment]
Fixed. I have to install 'libssl0.9.8' manually.

**Comment by joxeankoret** [comment]
No problem, is a common error in Linux.
