### ISSUE TITLE
Different results in using command line and GUI?

### ISSUE THREAD

**Issue by PangPangpeng** [joxeankoret/diaphora#90]
Hi,
  First thanks to your useful tool.
 ( I'm afraid of that the maillist is too slow, so I post the question again at here.)

[diaphora.zip](https://github.com/joxeankoret/diaphora/files/1505108/diaphora.zip)

  I want to use diaphora to generate .sqlite file automaticly so I followed the issues 70 on github. But  I got stucked when I using IDA command lines to generate .sqlite files. I put disphora folder into /IDA/python/ . And I wrote a script. Here's my script, I run it on windows.
`SET DIAPHORA_AUTO=1
SET DIAPHORA_EXPORT_FILE=D:\\diaphora\\aes.sqlite
SET DIAPHORA_USE_DECOMPILER=1
idaq.exe  -A -B -parm -Sdiaphora.py aes.o`
After while I got the aes.sqlite file. To confirm this file is correct, I opened aes.o and run diaphora in IDA  GUI. Then I got confused. The file size of the .sqlite file generated by IDA GUI is different from the .sqlite file generate by command line. But I open them in the SQLlite expert , I found they almost the same except the file size. So I think maybe the compare result is right? Then I compared GUI.sqlite with the third.sqlite(Sorry I didn't put it into the attachments), and compared GUI.sqlite with the third.sqlite. I got two different results. When I useing CMD.sqlite , I lost lots of "best matches".
So my question is :
  1.Why can't I get correct .sqlite file by running my scripts(I try it in the Ubuntu and I got the same result)?
  2.How Can I get the correct .sqlite file?
  3.Is there some method to generate .sqlite file without running ida pro?
To fix these question, I've tried lots of method, but not one works. Is there something I did wrong? Or I forget to add some args?
BTW, this aes.o file is an arm architecture static library. I put this three files into the attachments. CMD means generated by commandline, GUI meas generate by hand.
Help me out ,PLEASE!

**Comment by joxeankoret** [comment]
Hi @PangPangpeng: looking to the both databases, the only difference is that the one generated from the GUI is not using the Decompiler.

**Comment by PangPangpeng** [comment]
@joxeankoret Thank you for answer.  I put them into sqlite express and I get the same result as yours.  But I use the command "python diaphora.py GUI.sqlite third.sqlite -o result_gui.sqlite" get the first result. The I use the command "python diaphora.py CMD.sqlite third.sqlite -o result_cmd.sqlite"  get the second result. The first result is the same as I run this script in the IDA GUI. But the second result lost lots of "Best matches". I thought the reason that I get two different result is that  I get a wrong .sqlite file when I use IDA commandline. Now I get more confused......Could you give some more advise?  orz

**Comment by joxeankoret** [comment]
One question: which version of IDA are you using? 6.95, maybe?

**Comment by PangPangpeng** [comment]
@joxeankoret  I use IDA 6.8. Is it too old for this plugin?

**Comment by joxeankoret** [comment]
No, is not too old. But there might be bugs on IDA 6.8 that don't exists in newer versions. Actually, I only offer support for 6.9 and higher, but I will try to reproduce the bug on IDA 6.8 during this weekend and fix or workaround the possible problem(s).

**Comment by PangPangpeng** [comment]
@joxeankoret I got it . I'll try it on IDA7.0. Thank your for answering me question. :)
