### ISSUE TITLE
Exception while create sqlite

### ISSUE THREAD

**Issue by yairt** [joxeankoret/diaphora#93]
I tried to create SQLite DB using IDA 7.0 and latest Diaphora master code and got the following exception:
Error: 'NoneType' object has no attribute 'cases'
Traceback (most recent call last):
  File "C:/Tools/diaphora-master\diaphora_ida.py", line 1737, in _diff_or_export
    bd.export()
  File "C:/Tools/diaphora-master\diaphora_ida.py", line 599, in export
    self.do_export()
  File "C:/Tools/diaphora-master\diaphora_ida.py", line 572, in do_export
    props = self.read_function(func)
  File "C:/Tools/diaphora-master\diaphora_ida.py", line 1332, in read_function
    for idx in xrange(len(results.cases)):
AttributeError: 'NoneType' object has no attribute 'cases'

I will be able to provide the binary if needed, but I prefer to send it privately directly to the developer. If needed, please provide email address.

**Comment by joxeankoret** [comment]
This is a bug that comes from IDA not being able to read/parse a switch instruction. I have already committed a patch so it doesn't crashes but I would love to have the binary causing problems. You can use [this GPG key and e-mail](http://joxeankoret.com/contact.html) to share the binary.

**Comment by yairt** [comment]
Hi,

Do you have any news about this problem?

Thank you!
