### ISSUE TITLE
Issue with 'Out of memory' for a large IDB

### ISSUE THREAD

**Issue by rsk1588** [joxeankoret/diaphora#95]
The IDB file I have is 567MB. I am going through the first stage of exporting this for a diff on another IDB.

When it's going through exporting the functions, it throws an 'Out of memory' error at me after around 45 minutes of running the export. There are 189000~ functions in total and 217000~ in the new IDB. I am trying to switch to this from BinDiff as it is dreadfully slow (20 hours to complete a diff).

I am using the latest Diaphora build as of 29/11/2017 and IDA 7.

**Comment by joxeankoret** [comment]
I'm afraid there is little I can do here (~200k functions!), but I will try. Are you using the 32bit or 64bit version of IDA? If possible, try using the 64bit binary for IDA. It can be as easy as that because 64bit processes don't have the memory limitations that 32bit processes have.

**Comment by rsk1588** [comment]
Using 32bit IDA and the application is only a 32bit binary.

**Comment by joxeankoret** [comment]
Please try using the 64bit binary version of IDA. Not the IDA for 64bit binaries, but the 64bit binary of ida.exe or ida.

**Comment by rsk1588** [comment]
I'm trying the 64bit one now, I've had to another export which has taken me 3 hours so it's got a bit further than last time. Doing the diff now.

**Comment by rsk1588** [comment]
Please close this. Using 64bit worked for me.

**Comment by joxeankoret** [comment]
Glad to know it worked.
