### ISSUE TITLE
Form "Diaphora BinDiff" was not Free()d in IDA

### ISSUE THREAD

**Issue by xorstream** [joxeankoret/diaphora#96]
When using diaphora with IDA it prints the following error message to the output window when closing the current i64 file.
```WARNING: Form "Diaphora BinDiff" was not Free()d. Force-freeing.```

This occured when using IDA Pro 64bit v7 in Windows 10 64bit.
(I have not tested 32bit) 

Reproduction steps:
Start IDA 64bit and load in any i64 file.
Do "File->Script file" and select diaphora.py.
The diaphora form will be displayed.
Click cancel on the form.
Do "File->Close" to close the current database.
You should see the error message ```WARNING: Form "Diaphora BinDiff" was not Free()d. Force-freeing.``` in the output window.

Note: These are simple repo steps.
The issue also occurs when using diaphora normally such as clicking on OK on the diaphora form to perform export or diffing.

**Comment by joxeankoret** [comment]
I wonder if I can do anything with that. Thanks for pointing out, I will take a look!

**Comment by joxeankoret** [comment]
It seems there is nothing I can do :/
