### ISSUE TITLE
Can't seem to import more than one function in 'Best matches'

### ISSUE THREAD

**Issue by rsk1588** [joxeankoret/diaphora#98]
Can't seem to import more than one function in 'Best matches'. Get the below output (latest Diaphora):

`Type '#H' is already defined
Type '#w' is already defined
Type '#z' is already defined
Type '#�N' is already defined
Type '#�M' is already defined
Type '#�Q' is already defined
Type '#�U' is already defined
Type '#�]' is already defined
Type '#�p' is already defined
Type '#�s' is already defined
Type '#�u' is already defined
Type '#�x' is already defined
Type '#�{' is already defined
Type '#�I' is already defined
Type '#�A' is already defined
Type 'u_char' is already defined
Type 'u_long' is already defined
Type '#�D' is already defined
Type 'ULONG' is already defined
Syntax error near: _pragma
Syntax error near: }
Syntax error near: _pragma
Syntax error near: _pragma
Syntax error near: }
Syntax error near: _pragma
Syntax error near: _pragma
Syntax error near: }
Syntax error near: _pragma
Syntax error near: _pragma
Syntax error near: }
Plugin "hexrays" not found
Plugin "hexrays" not found`

**Comment by joxeankoret** [comment]
These lines aren't true errors but, rather, IDA's compilation errors when importing types (structures, enumerations, etc...). As there is no proper way that I can script to export this information and flawlessly import, what I do is to import all type various times and, at least the very first time, it fails compiling.

**Comment by rsk1588** [comment]
Ok the information doesn’t seem to get updated in the Names window. I will import all sub_ functions and the names will stay the same and not change. If I import one by one they change.

**Comment by joxeankoret** [comment]
One clarification @rsk1588: the function names don't get updated in the IDA's Names window (View -> Open Subviews -> Names) or in the Diaphora's own tabs?
