### ISSUE TITLE
Diaphora R2 is currently broken due to the last recent commits

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#99]
The following is a brief summary of what should be fixed in order to get it working back:

One new table has been added:

```
    sql = """create table if not exists callgraph (
                id integer primary key,
                func_id integer not null references functions(id) on delete cascade,
                address text not null,
                type text not null)"""
    cur.execute(sql)
```
 
In this table I insert all the callers and callees:

``` 
    # Save the callers and callees of the function
    callers, callees = props[len(props)-4:len(props)-2]
    sql = "insert into callgraph (func_id, address, type) values (?, ?, ?)"
    for caller in callers:
      cur.execute(sql, (func_id, caller, 'caller'))
   
    for callee in callees:
      cur.execute(sql, (func_id, callee, 'callee'))
```

I also added a new field to the table "functions": `assembly_addrs text`. In this field I insert a JSON list of all the addresses (sorted starting always from the entry point of the function). This list is used to match one-to-one assembly instructions from the origin database to the diffing database.

The relevant commits are the following ones:

1. https://github.com/joxeankoret/diaphora/commit/5351b6494315c71e1a2fddec5ac9304b9a997a77
2. https://github.com/joxeankoret/diaphora/commit/0836a6e8af1ca9a7ca8d9eaae77c3312be612deb

**Comment by joxeankoret** [comment]
Another comment to take into account although it isn't fundamental (as diaphora_r2.py is not able to use a decompiler yet, AFAIK):
https://github.com/joxeankoret/diaphora/commit/7db349c82822c36aefc54a403090b5d93a95d056

**Comment by radare** [comment]
yep it does. uses pdc, the internal pseudo-decompiler. but this command can be changed for another to select retdec or snowman. but this change should be implemented diaphora-wide, not r2-specific

**Comment by joxeankoret** [comment]
Pancake, whatever change you mention about how to tell radare2 which decompiler to use, is specific to radare2. Anyway.

**Comment by radare** [comment]
radare2 have no decompiler, just a pseudo-decompiler, it have plugins to support other decompilers, and all that is  unrelated to r2, but usable from r2, the same thing applies to ida, but as long as you’ll disagree, i’m not going to discuss this anymore

**Comment by pimentelo** [comment]
Related to this issue:

I tried running it as follows:
python diaphora_r2.py /bin/ls 

From:
~/.local/share/radare2/r2pm/git/diaphora

The output before it crashed was:

```
IMAGE BASE 4194304
FLOW [{u'inputs': 2, u'addr': 4213264, u'ninstr': 0, u'outputs': 2, u'traced': False, u'jump': 4213320, u'fail': 4213299, u'size': 35}, {u'inputs': 1, u'addr': 4213299, u'ninstr': 0, u'outputs': 2, u'traced': False, u'jump': 4213320, u'fail': 4213309, u'size': 10}, {u'inputs': 1, u'addr': 4213309, u'ninstr': 0, u'outputs': 1, u'traced': False, u'jump': 4213320, u'size': 11}, {u'inputs': 3, u'addr': 4213320, u'ninstr': 0, u'outputs': 0, u'traced': False, u'size': 2}, {u'inputs': 0, u'addr': 4213360, u'ninstr': 0, u'outputs': 2, u'traced': False, u'jump': 4213376, u'fail': 4213371, u'size': 11}, {u'inputs': 2, u'addr': 4213371, u'ninstr': 0, u'outputs': 1, u'traced': False, u'jump': 4213264, u'size': 2}, {u'inputs': 1, u'addr': 4213376, u'ninstr': 0, u'outputs': 2, u'traced': False, u'jump': 4213371, u'fail': 4213386, u'size': 10}, {u'inputs': 1, u'addr': 4213386, u'ninstr': 0, u'outputs': 1, u'traced': False, u'jump': 4213264, u'size': 12}]
BB 4213264 4213299
r2pipe.cmdj.Error: No JSON object could be decoded
Done
Error: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "diaphora_r2.py", line 1685, in _diff_or_export
    bd.export()
  File "diaphora_r2.py", line 545, in export
    self.do_export()
  File "diaphora_r2.py", line 518, in do_export
    props = self.read_function(func)
  File "diaphora_r2.py", line 1292, in read_function
    for succ_block in block_succs(block_startEA):
  File "diaphora_r2.py", line 77, in block_succs
    bb = bb[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
File created ls.sqlite
```

Line 77 seems to be to blame. There doesn’t seem to be a check for bb being None.

Alternatively if I try running it like this:
r2  -I diaphora_r2.py /bin/ls

I get the following output:

```
[Tue Jun 26 10:51:56 2018] name: 

[Tue Jun 26 10:51:56 2018] diaphora

Running from inside r2. Preserving the analysis information
LIST OF FUNCTION
r2pipe.cmdj.Error: No JSON object could be decoded
[ERROR] No functions found
LIST OF FUNCTION
r2pipe.cmdj.Error: No JSON object could be decoded
[ERROR] No functions found
Exporting database
LIST OF FUNCTION
r2pipe.cmdj.Error: No JSON object could be decoded
[ERROR] No functions found
FUNC LISTING IS []
c4e5f7fcbcef75924b2abde2b2e75f3f /bin/ls
MD5 
Done
[Tue Jun 26 10:51:57 2018] Database exported

File created 3432.sqlite
```

**Comment by joxeankoret** [comment]
Is anybody going to fix this at any time? Otherwise, I will be dropping the Radare support as it doesn't work since almost a year.

**Comment by joxeankoret** [comment]
I'm dropping the support for Radare2 because, well, it's been broken since almost a year.

**Comment by enovella** [comment]
Might take a look if I find some time. The only drawback is that heuristics (pseudo-code) may not work well in r2.

**Comment by radare** [comment]
?

**Comment by enovella** [comment]
Please @joxeankoret, do you mind reopening this issue? I might want to help in porting Diaphora into r2.

**Comment by joxeankoret** [comment]
I will only reopen it when there is working code, not before. It was closed because there was no interest whatsoever to fix it from January 2 to October 24 2018.

**Comment by brainstorm** [comment]
There was interest by me a few months ago and interest again in https://github.com/radareorg/radare2/issues/15072 :_(
